[[Trafodion 1133]] [[Trafodion 1088]] [[Trafodion 1481]]
Trafodion 1133 and Trafodion 1088 allow installer to add a node.

Trafodion 1481 seperates rpm installs into its own script so that it can be
run during an upgrade (to make sure all new packages needed are added). Bug still needs to be fixed is that it runs too many times (is ran once per node) and doesn't need to be. Will create a new jira for that small bug. Would like to check this in to prevent issue when upgrading.

diff --git a/install/installer/traf_cloudera_mods98 b/install/installer/traf_cloudera_mods98
--- a/install/installer/traf_cloudera_mods98
+++ b/install/installer/traf_cloudera_mods98
@@ -43,9 +43,13 @@ if [ "$JAVA_VERSION" == "1.6" ]; then
    exit -1
 elif [ "$JAVA_VERSION" == "1.7" ]; then
    if [[ $CDH_5_3_HDP_2_2_SUPPORT == "N" ]]; then
-      hbase_trx_jar="hbase-trx-${TRAF_VERSION}.jar"
+      if [[ $CDH_5_4_SUPPORT == "Y" ]]; then
+         hbase_trx_jar="hbase-trx-cdh5_4-${TRAF_VERSION}.jar"
+      else
+         hbase_trx_jar="hbase-trx-${TRAF_VERSION}.jar" 
+      fi 
    else
-       hbase_trx_jar="hbase-trx-cdh5_3-${TRAF_VERSION}.jar"      
+      hbase_trx_jar="hbase-trx-cdh5_3-${TRAF_VERSION}.jar"
    fi
 else
     echo "***ERROR: unable to determine Hadoop's java version"
@@ -121,8 +125,16 @@ sudo chmod 777 $TRAF_CONFIG
 source $TRAF_CONFIG
 
 #Copy hbase-site.xml file
+ssh -q -n $CDH_START_NODE sudo cp /etc/hbase/conf/hbase-site.xml $HOME
+ssh -q -n $CDH_START_NODE sudo chown $(whoami).$(whoami) $HOME/hbase-site.xml
+ssh -q -n $CDH_START_NODE sudo chmod 777 $HOME/hbase-site.xml
 
-scp -q $(whoami)@$CDH_START_NODE:/etc/hbase/conf/hbase-site.xml $TRAF_WORKDIR
+scp -q $(whoami)@$CDH_START_NODE:$HOME/hbase-site.xml $HOME
+if [[ $? -ne 0 ]]; then
+   echo "***ERROR: Unable to find /etc/hbase/conf/hbase-site.xml file on $CDH_START_NODE or unable to copy."
+   exit -1
+fi
+sudo cp $HOME/hbase-site.xml $TRAF_WORKDIR
 sudo chown trafodion.trafodion $TRAF_WORKDIR/hbase-site.xml
 
 
diff --git a/install/installer/traf_setup b/install/installer/traf_setup
--- a/install/installer/traf_setup
+++ b/install/installer/traf_setup
@@ -108,177 +108,15 @@ fi
 internetAccess=true
  
 #==========================================
-echo "***INFO: Installing required packages"
-echo "***INFO: Log file located in /var/log/trafodion"
-YUM_LOG=/var/log/trafodion/trafodion_yum_$timestamp.log
-ZYPP_LOG=/var/log/trafodion/trafodion_zypp_$timestamp.log
+#installing required packages"
 
-#================================
-#Checking to see if epel package is installed. 
-if [[ $SUSE_LINUX == "false" ]]; then
-   for node in $NODE_LIST;
-   do
-     EPEL_INSTALLED=$(ssh -q -n $node rpm -qa | grep epel | wc -l)
-     if [[ $EPEL_INSTALLED == 0 ]]; then
-        break;
-     fi
-   done
+$LOCAL_WORKDIR/traf_package_setup
 
-   if [[ $EPEL_INSTALLED == 0 ]]; then
-      echo "***INFO: ... EPEL rpm"
-      if [[ "$EPEL_RPM" != "" ]]; then
-         if [ $node_count -ne 1 ]; then
-            for node in $NODE_LIST
-            do
-               scp -q $EPEL_RPM $(whoami)@$node:$HOME
-            done
-         else
-            cp -rf $EPEL_RPM $HOME
-         fi
-      else
-         if [[ $internetAccess == "true" ]]; then
-            epel_rpm="epel-release-6-8.noarch.rpm"
-            wget http://download.fedoraproject.org/pub/epel/6/x86_64/$epel_rpm
-            if [ $node_count -ne 1 ]; then
-               for node in $NODE_LIST
-               do
-                  scp -q $LOCAL_WORKDIR/$epel_rpm $(whoami)@$node:$HOME
-               done
-            else
-               cp -rf $epel_rpm $HOME
-            fi
-
-            if [ $? != 0 ]; then
-               echo "***ERROR: Can't download EPEL rpm $epel_rpm"
-               echo "***ERROR: Please check http_proxy settings in .bashrc file"
-               echo
-               exit -1
-            fi 
-         else
-            echo "***ERROR: No EPEL RPM installed"
-            echo "***ERROR: No internet access to do automatic install."
-            exit -1         
-         fi
-      fi
-   fi
-
-   for node in $NODE_LIST;
-   do
-     EPEL_INSTALLED=$( ssh -q -n $node rpm -qa | grep epel | wc -l)
-     if [[ $EPEL_INSTALLED == 0 ]]; then
-        ssh -q -n $node sudo rpm -Uvh $HOME/epel* 2>> $YUM_LOG >> $YUM_LOG
-        if [ $? != 0 ]; then
-           echo "***ERROR: Can't install EPEL rpm $EPEL_RPM"
-           exit -1
-        fi
-     fi
-   done
-
-else
-   echo 
-   echo
-   echo 
-   echo "***WARNING: This system is using SUSE Linux"
-   echo "***WARNING: pdsh must be installed prior to installing Trafodion."
-   echo "***WARNING: If pdsh has not been installed. Please stop the installer and install pdsh"
-   echo 
-   echo 
-   sleep 10
+if [ $? != 0 ]; then
+    echo "***ERROR: Error installing required packages"
+    exit -1
 fi
 
-#install pdsh if not on SUSE Linux
-if [[ $SUSE_LINUX == "false" ]]; then
-   if [ $node_count -ne 1 ]; then
-      for node in $NODE_LIST
-      do
-          echo "***INFO: ... pdsh on node $node"
-          #if not already installed on this node, then install it
-          ssh -q -n $node rpm -qa | grep pdsh &> /dev/null
-          if [ $? -ne 0 ]; then
-             ssh -q -n $node sudo mkdir -p $TRAF_WORKDIR
-             ssh -q -n $node sudo mkdir -p /var/log/trafodion
-             if [[ $internetAccess == "true" ]]; then
-                ssh -q -n $node sudo yum --assumeyes install pdsh >> $YUM_LOG
-                if [ $? != 0 ]; then
-                   echo "***ERROR: Can't install pdsh on node $node"
-                   exit -1
-                fi
-             else
-                echo "***ERROR: Can't install pdsh on node $node"
-                echo "***ERROR: Must have pdsh installed on each node."
-                echo "***ERROR: No internet access to do automatic install."
-                exit -1
-             fi
-          fi
-      done
-      # create working directory on all nodes
-      $TRAF_PDSH sudo mkdir -p $TRAF_WORKDIR &> /dev/null
-      $TRAF_PDSH sudo chmod -R 777 $TRAF_WORKDIR
-      $TRAF_PDSH mkdir -p /var/log/trafodion &> /dev/null
-
-   fi
-fi
-
-$TRAF_PDSH sudo mkdir -p $TRAF_WORKDIR
-$TRAF_PDSH sudo chmod 777 $TRAF_WORKDIR
-
-if [[ $SUSE_LINUX == "false" ]]; then
-   # to handle the case where the EPEL rpm was already
-   # installed but disabled, we enable it here
-   # it doesn't hurt if it was already enabled and we try to enable it again
-   $TRAF_PDSH sudo yum-config-manager --enable RedHat-6-x86_64-Fedora-EPEL 2>> $YUM_LOG >> $YUM_LOG
-
-   package_list="log4cxx sqlite "
-   package_list+="expect perl-DBD-SQLite* protobuf xerces-c "
-   package_list+="perl-Params-Validate perl-Time-HiRes gzip"
-
-   if [[ $internetAccess == "true" ]]; then
-      for package in $package_list
-      do
-         echo "***INFO: Checking if $package is installed ..."
-         for node in $NODE_LIST
-         do
-            installed=`ssh -q -n $node sudo rpm -qa | grep $package | wc -l`
-            if [[ $installed -eq "0" ]]; then
-               echo "***INFO: Installing $package on all nodes"
-               ssh -q -n $node sudo yum --assumeyes install $package 2>> $YUM_LOG >> $YUM_LOG
-               if [ $? != 0 ]; then
-                  echo "***ERROR: Can't install $package"
-                  exit -1
-               fi
-               break
-            fi
-         done
-      done
-   else
-      for node in $NODE_LIST
-      do
-         echo "***ERROR: No internet access on $node"
-         echo "***ERROR: Missing packages will need to be installed."
-         echo "***ERROR: Missing packages: " 
-         for package in $package_list
-         do
-             installed=$(sudo rpm -qa | grep $package | wc -l)
-             if [[ $installed -eq "0" ]]; then
-                echo "$package"
-                stopInstall=true
-             fi
-         done
-      done
-      if [[ $stopInstall == "true" ]]; then
-         exit -1   
-      fi
-   fi
-else
-   echo
-   echo 
-   echo "***WARNING: All needed RPM's must be installed in advance to install Trafodion on SUSE."
-   echo "***WARNING: log4cxx sqlite expect perl-DBD-SQLite* protobuf xerces-c perl-Params-Validate perl-Time-HiRes gzip"
-   echo "***WARNING: If any of these packages have not been installed. Stop Trafodion installation and install."
-   echo 
-   echo 
-   sleep 10
-fi
 #================================
 # Set some limits needed by Trafodion
 
