TRAFODION [109] Instrument Trafodion to work with Secure Hadoop (Kerberos)
The first phase of automation with Kerberos is ready.

The following use cases are supported

I.	New secure install: Customer installs Trafodion on a cluster with
 secure Hadoop. There is no existing Trafodion installation.

II.	Conversion from non-secure to secure: Customer has Trafodion installed
on a non-secure Hadoop cluster. Customer enables Hadoop security on this
existing cluster. Customer runs a Trafodion script to enable Hadoop security
integration with Trafodion.

See the JIRA for details on the changes.

diff --git a/install/installer/traf_cloudera_mods b/install/installer/traf_cloudera_mods
--- a/install/installer/traf_cloudera_mods
+++ b/install/installer/traf_cloudera_mods
@@ -35,6 +35,22 @@ export PDSH_HADOOP_NODES="$PDSH $MY_HBASE_NODES $PDSH_SSH_CMD"
 export PDCP_HADOOP_NODES="$PDCP $MY_HBASE_NODES"
 export HDFS_NODE=$(echo $HDFS_NODES | head -n1 | awk '{print $1;}')
 export HBASE_NODE=$(echo $HBASE_NODES | head -n1 | awk '{print $1;}')
+
+#=====================================
+# create principals for hdfs user if secure hadoop is enabled
+if [[ $SECURE_HADOOP == "Y" ]]; then
+   REALM=${ADMIN_PRINCIPAL#*"@"}
+   HDFS_PRINCIPAL=$(sudo klist -kte $HDFS_KEYTAB |grep $REALM | grep 'hdfs/' | awk '{print $4}' | uniq)
+   MESSAGE="***INFO: obtain and cache the Kerberos ticket-granting ticket for hdfs user"
+   MESSAGE=$MESSAGE"  using keytab $HDFS_KEYTAB and principal $HDFS_PRINCIPAL"
+   echo $MESSAGE
+   sudo -u $HDFS_USER kinit -kt $HDFS_KEYTAB $HDFS_PRINCIPAL
+   if [ $? != 0 ]; then
+      echo "***ERROR: failed to obtain and cache the Kerberos ticket-granting ticket for hdfs user"
+      exit -1
+   fi
+fi
+
 #=====================================
 # copy Trafodion trx jar to Cloudera's plugins directory on all nodes
 
diff --git a/install/installer/trafodion_install b/install/installer/trafodion_install
--- a/install/installer/trafodion_install
+++ b/install/installer/trafodion_install
@@ -363,6 +363,14 @@ else
    sudo chmod 777 $TRAF_CONFIG
 fi
 
+# prompt user for configuration info
+$LOCAL_WORKDIR/traf_secure_setup | tee -a $INSTALL_LOG
+if [ ${PIPESTATUS[0]} != "0" ]; then
+   echo "***ERROR: Error while running traf_secure_setup." | tee -a $INSTALL_LOG
+   echo "***ERROR: No security configuration file created." | tee -a $INSTALL_LOG
+   exit -1
+fi
+
 source $TRAF_CONFIG
 if [ $? -ne 0 ]; then
    echo "***ERROR: unable to source $TRAF_CONFIG"
@@ -627,35 +635,6 @@ if [[ "$all_node_count" -ne "1" ]]; then
    $TRAF_PDSH sudo mkdir -p /$HOME_DIR/$TRAF_USER/installer &> /dev/null
 fi
 
-#Copy over traf_authentication_config file to all nodes
-if [[ "$LDAP_SECURITY" == "Y" ]]; then
-   echo "***INFO: Copying $LDAP_AUTH_FILE to Trafodion home dir"
-
-   if [[ "$all_node_count" -eq "1" ]]; then
-      sudo cp -r $LOCAL_WORKDIR/$LDAP_AUTH_FILE $HOME_DIR/$TRAF_USER
-      sudo chown trafodion.trafodion $HOME_DIR/$TRAF_USER/$LDAP_AUTH_FILE
-      sudo chmod 750 $HOME_DIR/$TRAF_USER/$LDAP_AUTH_FILE
-      if [[ $LDAP_LEVEL == "2" ]] || [[ $LDAP_LEVEL == "1" ]]; then
-         echo "***INFO: Copying $LDAP_CERT to Trafodion home dir"
-         sudo cp -r $LDAP_CERT $HOME_DIR/$TRAF_USER
-         sudo chown trafodion.trafodion $HOME_DIR/$TRAF_USER/$LDAP_CERT_BASE
-         sudo chmod 750 $HOME_DIR/$TRAF_USER/$LDAP_CERT_BASE
-      fi
-   else
-      $TRAF_PDCP $LOCAL_WORKDIR/$LDAP_AUTH_FILE $HOME
-      $TRAF_PDSH sudo cp -r $HOME/$LDAP_AUTH_FILE $HOME_DIR/$TRAF_USER
-      $TRAF_PDSH sudo chown trafodion.trafodion $HOME_DIR/$TRAF_USER/$LDAP_AUTH_FILE
-      $TRAF_PDSH sudo chmod 750 $HOME_DIR/$TRAF_USER/$LDAP_AUTH_FILE
-      if [[ $LDAP_LEVEL == "2" ]] || [[ $LDAP_LEVEL == "1" ]]; then
-         echo "***INFO: Copying $LDAP_CERT to Trafodion home dir"
-         $TRAF_PDCP $LDAP_CERT $HOME
-         $TRAF_PDSH sudo cp -r $HOME/$LDAP_CERT_BASE $HOME_DIR/$TRAF_USER
-         $TRAF_PDSH sudo chown trafodion.trafodion $HOME_DIR/$TRAF_USER/$LDAP_CERT_BASE
-         $TRAF_PDSH sudo chmod 750 $HOME_DIR/$TRAF_USER/$LDAP_CERT_BASE
-      fi
-   fi
-fi
-
 #=============================================
 #Run trafodion_mods
 
@@ -704,6 +683,25 @@ fi
 
 echo "***INFO: Trafodion Mods ran successfully."
 
+#==============================================
+#Secure Hadoop setup for Trafodion
+if [[ "$SECURE_HADOOP" == "Y" ]]; then
+   echo
+   echo "******************************"
+   echo " TRAFODION SECURE HADOOP SETUP"
+   echo "******************************"
+   echo
+   echo "***INFO: Running Kerberos installation"
+   $LOCAL_WORKDIR/traf_add_kerberos | tee -a $INSTALL_LOG
+   if [ ${PIPESTATUS[0]} != "0" ]; then
+      echo "***ERROR: Error while running traf_add_kerberos." | tee -a $INSTALL_LOG
+      echo "***ERROR: Kerberos not enabled" | tee -a $INSTALL_LOG
+      exit -1
+   fi
+fi
+
+echo "***INFO: Secure Hadoop setup for Trafodion ran successfully."
+
 #Get HBaseSite.xml information 
 $LOCAL_WORKDIR/parseHBaseSite.py
 #==============================================
@@ -726,6 +724,16 @@ if [ ${PIPESTATUS[0]} != "0" ]; then
    exit -1
 fi
 
+# setup identity store (LDAP) stuff
+if [[ "$LDAP_SECURITY" == "Y" ]]; then
+   $LOCAL_WORKDIR/traf_add_ldap | tee -a $INSTALL_LOG
+   if [ ${PIPESTATUS[0]} != "0" ]; then
+      echo "***ERROR: Error while running traf_add_ldap." | tee -a $INSTALL_LOG
+      echo "***ERROR: ldap not enabled" | tee -a $INSTALL_LOG
+      exit -1
+   fi
+fi
+
 # Install and configure CLI for Cloud environments
 if  [ "$ENABLE_HA" == "true" ] && [[ $CLOUD_CONFIG == "Y" ]] && [[ $all_node_count -gt 1 ]]; then
   echo "***INFO: Install and configure CLI for Cloud"
@@ -741,8 +749,19 @@ if [[ $START_ALL == "Y" ]]; then
       echo "***ERROR: Setup not complete, review logs." | tee -a $INSTALL_LOG
       echo "***ERROR: Exiting...." | tee -a $INSTALL_LOG
      exit -1
-  fi
+   fi
+
+   if [[ "$LDAP_SECURITY" == "Y"  || "$SECURE_HADOOP" == "Y" ]]; then
+      echo "***INFO: Configure authorization"
+      sudo su $TRAF_USER --login --command "$TRAF_WORKDIR/installer/traf_secure" 2>&1 | tee -a $INSTALL_LOG
+
+      if [ ${PIPESTATUS[0]} != "0" ]; then
+         echo "***ERROR: Error while running traf_secure." | tee -a $INSTALL_LOG
+         echo "***ERROR: Security setup not complete, continuing - review logs." | tee -a $INSTALL_LOG
+      fi
+   fi
 fi
+
 #==============================================
 MODS_COMPLETE="N"
 sudo chmod 777 $TRAF_CONFIG
