Documentation and installer change for Floating IP

diff --git a/install/installer/traf_config_setup b/install/installer/traf_config_setup
--- a/install/installer/traf_config_setup
+++ b/install/installer/traf_config_setup
@@ -63,6 +63,7 @@ FLOATING_IP=""
 BACKUP_DCS_NODES=""
 LDAP_SECURITY="N"
 SCANNER_MODE="N"
+DCS_PRIMARY_MASTER_NODE=`hostname`
 
 LDAP_LEVEL="0"
 #==============================================
@@ -155,6 +156,44 @@ echo "export TRAF_USER=\"$TRAF_USER\"" >> $LOCAL_TRAF_CONFIG
 echo "export TRAF_WORKDIR=\"$TRAF_WORKDIR\"" >> $LOCAL_TRAF_CONFIG
 echo "export LOCAL_WORKDIR=\"$LOCAL_WORKDIR\"" >> $LOCAL_TRAF_CONFIG
 echo "export SQCONFIG=\"$SQCONFIG\"" >> $LOCAL_TRAF_CONFIG
+
+#==============================================
+#Check if customer is using cloud environment and get the type of cloud being used
+#Get the CLOUD_CONFIG and CLOUD_TYPE
+echo -n "Is this a cloud environment (Y/N), default is N: "
+read answer
+
+if [ ! -z $answer ]; then
+   if [[ "${answer}" =~ ^[Yy]$ ]]; then
+         CLOUD_CONFIG="Y"
+      fi
+   else 
+      CLOUD_CONFIG="N"
+fi
+
+echo "export CLOUD_CONFIG=\"$CLOUD_CONFIG\"" >> $LOCAL_TRAF_CONFIG
+
+if [[ "$CLOUD_CONFIG" == "Y" ]]; then
+  echo -n "Specify the type of cloud being used (1: AWS(Amazon cloud), 2: OpenStack, 3: Other): "
+  read answer1
+  if [[ -z "$answer1" ]]; then
+     echo "***ERROR: Must specify the type of Cloud being used."
+     exit -1
+  else
+     CLOUD_TYPE=$answer1
+  fi
+  echo "export CLOUD_TYPE=\"$CLOUD_TYPE\"" >> $LOCAL_TRAF_CONFIG
+  case "$CLOUD_TYPE" in 
+    1) AWS_CLOUD=true
+       echo "export AWS_CLOUD=\"$AWS_CLOUD\"" >> $LOCAL_TRAF_CONFIG
+       ;;
+    2) OPEN_STACK=true
+       echo "export OPEN_STACK=\"$OPEN_STACK\"" >> $LOCAL_TRAF_CONFIG
+       ;;
+    3) CLOUD_OTHER=true
+       echo "export CLOUD_OTHER=\"$CLOUD_OTHER\"" >> $LOCAL_TRAF_CONFIG
+  esac
+fi
 
 #==============================================
 # Password
@@ -472,6 +511,18 @@ fi
 echo "export DCS_SERVERS_PARM=\"$DCS_SERVERS_PARM\"" >> $LOCAL_TRAF_CONFIG
 
 #==============================================
+#Get the node name where the customer would like to start DcsMaster process
+
+echo -n "Specify the node of DcsMaster process, default [$DCS_PRIMARY_MASTER_NODE]: "
+read answer
+
+if [ ! -z $answer ]; then
+   DCS_PRIMARY_MASTER_NODE="$answer"
+fi
+
+echo "export DCS_PRIMARY_MASTER_NODE=\"$DCS_PRIMARY_MASTER_NODE\"" >> $LOCAL_TRAF_CONFIG
+
+#==============================================
 #Enable HA
 
 echo -n "Enable High Availability (Y/N), default is N: "
@@ -490,65 +541,44 @@ fi
 echo "export ENABLE_HA=\"$ENABLE_HA\"" >> $LOCAL_TRAF_CONFIG
 
 #==============================================
-#Add Floating IP if HA Enabled
+#Get the floating IP address, interface name and the list of backup nodes to be used 
 if [[ "$ENABLE_HA" == "true" ]]; then
-   echo -n "Enter Floating IP address for DCS HA, default [$FLOATING_IP]: "
-   read answer
+   ######Get the floating IP address 
+   echo -n "Enter floating IP address for setting up HA: "
+   read answer1
 
-   if [ -z $answer ]; then
-      if [[ -z $FLOATING_IP ]]; then
-         echo "***ERROR: Floating IP address not given." 
-         echo "***ERROR: Install will continue but WITHOUT High Availability"
-         echo "***ERROR: HA can be configured later, or kill this script and start over."
-         sed -i '/ENABLE_HA\=/d' $LOCAL_TRAF_CONFIG
-         echo "export ENABLE_HA=\"false\"" >> $LOCAL_TRAF_CONFIG     
-      fi      
+   if [[ -z $answer1 ]]; then
+         echo "Floating IP address must be specified."
+         exit 1
    else
-      FLOATING_IP="$answer"
+      FLOATING_IP="$answer1"
    fi
    echo "export FLOATING_IP=\"$FLOATING_IP\"" >> $LOCAL_TRAF_CONFIG
-fi
 
+   ######Get the interface used by the floating IP address
+   echo -n "Enter interface used for floating IP address: "
+   read answer2
 
-#==============================================
-#Add Floating IP if HA Enabled
-if [[ "$ENABLE_HA" == "true" ]]; then
-   echo -n "Enter interface for Floating IP address (example: eth0), default [$INTERFACE]: "
-   read answer
-
-   if [ -z $answer ]; then
-      if [[ -z $INTERFACE ]]; then
-         echo "***ERROR: Floating IP interface was not given."
-         echo "***ERROR: Install will contiune but WITHOUT High Availability"
-         echo "***ERROR: HA can be configured later, or kill this script and start over."
-         sed -i '/ENABLE_HA\=/d' $LOCAL_TRAF_CONFIG
-         echo "export ENABLE_HA=\"false\"" >> $LOCAL_TRAF_CONFIG
-      fi
+   if [ -z $answer2 ]; then
+      echo "Floating IP address interface name must be specified."
+      exit 1
    else
-      INTERFACE="$answer"
+      INTERFACE="$answer2"
    fi
    echo "export INTERFACE=\"$INTERFACE\"" >> $LOCAL_TRAF_CONFIG
-fi
 
-#==============================================
-#Add Backup DCS Master nodes if HA Enabled
-if [[ "$ENABLE_HA" == "true" ]]; then
-   echo -n "Enter DCS Backup Master Nodes for DCS HA, default [$BACKUP_DCS_NODES]: "
-   read answer 
+   ######Get the list of backup nodes to be used
+   echo -n "Enter backup nodes for HA (blank seperated): "
+   read answer3 
   
-   if [[ -z "$answer" ]]; then 
-      if [[ -z "$BACKUP_DCS_NODES" ]]; then
-         echo "***ERROR: Backup DCS Nodes not given."
-         echo "***ERROR: Install will contiune but WITHOUT High Availability"
-         echo "***ERROR: HA can be configured later, or kill this script and start over."
-         sed -i '/ENABLE_HA\=/d' $LOCAL_TRAF_CONFIG
-         echo "export ENABLE_HA=\"false\"" >> $LOCAL_TRAF_CONFIG 
-      fi
+   if [[ -z "$answer3" ]]; then 
+      echo "Backup nodes must be specified."
+      exit 1
    else
-      BACKUP_DCS_NODES="$answer"
+      BACKUP_DCS_NODES="$answer3"
    fi
    echo "export BACKUP_DCS_NODES=\"$BACKUP_DCS_NODES\"" >> $LOCAL_TRAF_CONFIG
-fi 
+fi
 
 #==============================================
 #Simple security
@@ -645,7 +675,7 @@ if [[ $SCANNER_MODE == "N" ]]; then
       read answer4
       if [[ -z "$answer4" ]]; then
          if [ -z "$LDAP_LEVEL" ]; then
-            echo "***ERROR: Much enter LDAP Encryption level."
+            echo "***ERROR: Must enter LDAP Encryption level."
             exit -1
          fi
       else
