TRAFODION [109] Instrument Trafodion to work with Secure Hadoop (Kerberos)
Fixed issue where Jenkins installation was failing.
Fixed problem where Kerberos ticket was not being initialized on all nodes
without logging on.
Fixed an issue with uninstall

diff --git a/install/installer/trafodion_install b/install/installer/trafodion_install
--- a/install/installer/trafodion_install
+++ b/install/installer/trafodion_install
@@ -353,6 +353,14 @@ if [ -z "$USER_CONFIG" ]; then
       echo "***ERROR: No configuration file created." | tee -a $INSTALL_LOG
       exit -1
    fi
+
+   # prompt user for security configuration info
+   $LOCAL_WORKDIR/traf_secure_setup | tee -a $INSTALL_LOG
+   if [ ${PIPESTATUS[0]} != "0" ]; then
+      echo "***ERROR: Error while running traf_secure_setup." | tee -a $INSTALL_LOG
+      echo "***ERROR: No security configuration file created." | tee -a $INSTALL_LOG
+      exit -1
+   fi
 else
    # copy the user's config file to the default location
    sudo cp $USER_CONFIG $TRAF_CONFIG
@@ -361,14 +369,6 @@ else
       exit -1
    fi
    sudo chmod 777 $TRAF_CONFIG
-fi
-
-# prompt user for configuration info
-$LOCAL_WORKDIR/traf_secure_setup | tee -a $INSTALL_LOG
-if [ ${PIPESTATUS[0]} != "0" ]; then
-   echo "***ERROR: Error while running traf_secure_setup." | tee -a $INSTALL_LOG
-   echo "***ERROR: No security configuration file created." | tee -a $INSTALL_LOG
-   exit -1
 fi
 
 source $TRAF_CONFIG
@@ -683,25 +683,6 @@ fi
 
 echo "***INFO: Trafodion Mods ran successfully."
 
-#==============================================
-#Secure Hadoop setup for Trafodion
-if [[ "$SECURE_HADOOP" == "Y" ]]; then
-   echo
-   echo "******************************"
-   echo " TRAFODION SECURE HADOOP SETUP"
-   echo "******************************"
-   echo
-   echo "***INFO: Running Kerberos installation"
-   $LOCAL_WORKDIR/traf_add_kerberos | tee -a $INSTALL_LOG
-   if [ ${PIPESTATUS[0]} != "0" ]; then
-      echo "***ERROR: Error while running traf_add_kerberos." | tee -a $INSTALL_LOG
-      echo "***ERROR: Kerberos not enabled" | tee -a $INSTALL_LOG
-      exit -1
-   fi
-fi
-
-echo "***INFO: Secure Hadoop setup for Trafodion ran successfully."
-
 #Get HBaseSite.xml information 
 $LOCAL_WORKDIR/parseHBaseSite.py
 #==============================================
@@ -723,6 +704,25 @@ if [ ${PIPESTATUS[0]} != "0" ]; then
    echo "***ERROR: Exiting...." | tee -a $INSTALL_LOG
    exit -1
 fi
+
+#==============================================
+#Secure Hadoop setup for Trafodion
+if [[ "$SECURE_HADOOP" == "Y" ]]; then
+   echo
+   echo "******************************"
+   echo " TRAFODION SECURE HADOOP SETUP"
+   echo "******************************"
+   echo
+   echo "***INFO: Running Kerberos installation"
+   $LOCAL_WORKDIR/traf_add_kerberos | tee -a $INSTALL_LOG
+   if [ ${PIPESTATUS[0]} != "0" ]; then
+      echo "***ERROR: Error while running traf_add_kerberos." | tee -a $INSTALL_LOG
+      echo "***ERROR: Kerberos not enabled" | tee -a $INSTALL_LOG
+      exit -1
+   fi
+fi
+
+echo "***INFO: Secure Hadoop setup for Trafodion ran successfully."
 
 # setup identity store (LDAP) stuff
 if [[ "$LDAP_SECURITY" == "Y" ]]; then
