Many bug fixes. All JIRAs listed below.
TRAFODION-1545 Adding Management nodes
TRAFODION-1691 Smaller subscripts
Trafodion-1681 Need full HADOOP path for hdfs
Trafodion-1689 DCS HA
Trafodion-1756 kernel.pid_max persistent on reboot
Trafodion-1694 kernel.pid_max full path
Trafodion-1693 CLUSTERNAME being set
Trafodion-1574 Increasing maintainability of scripts
Trafodion-1711 curl commands should accept http/https
Trafodion-1478 Create /hbase/archive/data/default

diff --git a/install/installer/traf_cloudera_mods98 b/install/installer/traf_cloudera_mods98
--- a/install/installer/traf_cloudera_mods98
+++ b/install/installer/traf_cloudera_mods98
@@ -58,6 +58,7 @@ fi
 
 traf_util_jar="trafodion-utility-${TRAF_VERSION}.jar"
 
+
 # The permissions the Trafodion build process creates on the hbase-trx jar
 # files does not work well with the installation process so we change them
 sudo chmod -R 777 $UNTAR_DIR/export/lib
@@ -118,42 +119,42 @@ sudo chmod 777 $HOME/hbase-site.xml
 sudo cp $HOME/hbase-site.xml $TRAF_WORKDIR
 sudo chown trafodion.trafodion $TRAF_WORKDIR/hbase-site.xml
 
-sudo su $HDFS_USER --command "hadoop fs -mkdir /hbase-staging" 2> $HOME/traf_temp_output
+sudo su $HDFS_USER --command "$HADOOP_BIN_PATH/hadoop fs -mkdir /hbase-staging" 2> $HOME/traf_temp_output
 if [ $? != 0 ]; then
    # ok if directory already exists
    dir_exists=$(grep "File exists" $HOME/traf_temp_output | wc -l)
    if [ $dir_exists -eq 0 ]; then
-      echo "***ERROR: 'hadoop fs -mkdir /hbase-staging' command failed"
+      echo "***ERROR: '$HADOOP_BIN_PATH/hadoop fs -mkdir /hbase-staging' command failed"
       echo "***ERROR: $(cat $HOME/traf_temp_output)"
       exit -1
    fi
 fi
 
-sudo su $HDFS_USER --command "hadoop fs -chown -R $HBASE_USER:$HBASE_GROUP /hbase-staging"
-sudo su $HDFS_USER --command "hadoop fs -mkdir /bulkload" 2> $HOME/traf_temp_output
+sudo su $HDFS_USER --command "$HADOOP_BIN_PATH/hadoop fs -chown -R $HBASE_USER:$HBASE_GROUP /hbase-staging"
+sudo su $HDFS_USER --command "$HADOOP_BIN_PATH/hadoop fs -mkdir /bulkload" 2> $HOME/traf_temp_output
 if [ $? != 0 ]; then
    # ok if directory already exists
    dir_exists=$(grep "File exists" $HOME/traf_temp_output | wc -l)
    if [ $dir_exists -eq 0 ]; then
-      echo "***ERROR: 'hadoop fs -mkdir /bulkload' command failed"
+      echo "***ERROR: '$HADOOP_BIN_PATH/hadoop fs -mkdir /bulkload' command failed"
       echo "***ERROR: $(cat $HOME/traf_temp_output)"
       exit -1
    fi
 fi
-sudo su $HDFS_USER --command "hadoop fs -chown -R $TRAF_USER:trafodion /bulkload"
+sudo su $HDFS_USER --command "$HADOOP_BIN_PATH/hadoop fs -chown -R $TRAF_USER:trafodion /bulkload"
 
 # Create lobs directory
-sudo su $HDFS_USER --command "hadoop fs -mkdir /lobs" 2> $HOME/traf_temp_output
+sudo su $HDFS_USER --command "$HADOOP_BIN_PATH/hadoop fs -mkdir /lobs" 2> $HOME/traf_temp_output
 if [ $? != 0 ]; then
    # ok if directory already exists
    dir_exists=$(grep "File exists" $HOME/traf_temp_output | wc -l)
    if [ $dir_exists -eq 0 ]; then
-      echo "***ERROR: 'hadoop fs -mkdir /lobs' command failed"
+      echo "***ERROR: '$HADOOP_BIN_PATH/hadoop fs -mkdir /lobs' command failed"
       echo "***ERROR: $(cat $LOCAL_WORKDIR/traf_temp_output)"
       exit -1
    fi
 fi
-sudo su $HDFS_USER --command "hadoop fs -chown -R $TRAF_USER:trafodion /lobs"
+sudo su $HDFS_USER --command "$HADOOP_BIN_PATH/hadoop fs -chown -R $TRAF_USER:trafodion /lobs"
 
 #=====================================
 # Modify hadoop settings as needed by Trafodion
@@ -162,7 +163,7 @@ rm $HOME/traf_hdfs1_config_temp 2> /dev/null
 rm $HOME/traf_hbase_config_temp 2> /dev/null
 
 # change the hdfs configuration using Cloudera's REST API
-curl -X PUT -H 'Content-Type:application/json' -u $ADMIN:$PASSWORD  --data \
+curl -k -X PUT -H 'Content-Type:application/json' -u $ADMIN:$PASSWORD  --data \
 '{ "roleTypeConfigs" :  [ {
         "roleType" : "NAMENODE",
         "items": [ {
@@ -181,7 +182,7 @@ curl -X PUT -H 'Content-Type:application/json' -u $ADMIN:$PASSWORD  --data \
              "value":"true"
              } ]
 }' \
-http://$URL/api/v1/clusters/$CLUSTER_NAME/services/hdfs/config > $LOCAL_WORKDIR/traf_hdfs_config_temp
+$URL/api/v1/clusters/$CLUSTER_NAME/services/hdfs/config > $LOCAL_WORKDIR/traf_hdfs_config_temp
 
 if [ $? != 0 ]; then
     echo "***ERROR: Unable to modify HDFS configuration through Cloudera's REST API."
@@ -211,7 +212,7 @@ rm $LOCAL_WORKDIR/traf_hdfs_config_temp 2> /dev/null
 # NOTE: hbase.regionserver.lease.period is used as it is equivalent to
 #       hbase.client.scanner.timeout.period and Cloudera only allows
 #       hbase.regionserver.lease.period to be set through the REST API.
-curl -X PUT -H 'Content-Type:application/json' -u $ADMIN:$PASSWORD  --data \
+curl -k -X PUT -H 'Content-Type:application/json' -u $ADMIN:$PASSWORD  --data \
 '{ "roleTypeConfigs" :	[ {
 	"roleType" : "MASTER",
 	"items" : [ { 
@@ -232,7 +233,7 @@ curl -X PUT -H 'Content-Type:application/json' -u $ADMIN:$PASSWORD  --data \
 		} ] 
 	} ] 
 }' \
-http://$URL/api/v1/clusters/$CLUSTER_NAME/services/$HBASE/config > $LOCAL_WORKDIR/traf_hbase_config_temp
+$URL/api/v1/clusters/$CLUSTER_NAME/services/$HBASE/config > $LOCAL_WORKDIR/traf_hbase_config_temp
 
 if [ $? != 0 ]; then
     echo "***ERROR: Unable to modify HBase configuration through Cloudera's REST API."
@@ -260,7 +261,7 @@ rm $LOCAL_WORKDIR/traf_hbase_config_temp 2> /dev/null
 
 # Change zookeeper config using Cloudera REST API
 
-curl -X PUT -H 'Content-Type:application/json' -u $ADMIN:$PASSWORD  --data \
+curl -k -X PUT -H 'Content-Type:application/json' -u $ADMIN:$PASSWORD  --data \
 '{ "roleTypeConfigs" :  [ {
         "roleType" : "SERVER",
         "items": [ {
@@ -270,7 +271,7 @@ curl -X PUT -H 'Content-Type:application/json' -u $ADMIN:$PASSWORD  --data \
         } ]
 
 }' \
-http://$URL/api/v1/clusters/$CLUSTER_NAME/services/zookeeper/config > $LOCAL_WORKDIR/traf_zookeeper_config_temp
+$URL/api/v1/clusters/$CLUSTER_NAME/services/zookeeper/config > $LOCAL_WORKDIR/traf_zookeeper_config_temp
 
 # in most cases curl does not return an error
 # so curl's actual output needs to be checked, too
@@ -296,8 +297,8 @@ rm $LOCAL_WORKDIR/traf_zookeeper_config_temp 2> /dev/null
 poll_time=30
 echo "***INFO: restarting Hadoop to pickup Trafodion transaction jar"
 echo "***INFO: ...polling every $poll_time seconds until restart is completed."
-restart_info=$(curl -X POST -u $ADMIN:$PASSWORD \
-    http://$URL/api/v1/clusters/$CLUSTER_NAME/commands/restart)
+restart_info=$(curl -k -X POST -u $ADMIN:$PASSWORD \
+    $URL/api/v1/clusters/$CLUSTER_NAME/commands/restart)
 echo $restart_info
 command_id=$(echo $restart_info | grep id | awk '{print $4}' | sed -e 's@,@@' )
 echo "***DEBUG: Cloudera command_id=$command_id"
@@ -306,8 +307,8 @@ echo "***DEBUG: Cloudera command_id=$command_id"
 active=1
 while [ $active -ne 0 ]; do
     sleep $poll_time
-    curl -u $ADMIN:$PASSWORD \
-        http://$URL/api/v1/commands/$command_id \
+    curl -k -u $ADMIN:$PASSWORD \
+        $URL/api/v1/commands/$command_id \
         > $LOCAL_WORKDIR/hbase_restart_status_temp
     cat $LOCAL_WORKDIR/hbase_restart_status_temp
     echo "***INFO: ...polling every $poll_time seconds until restart is completed."
@@ -326,37 +327,59 @@ echo "***INFO: Hadoop restart completed successfully"
 
 # wait to make sure HDFS is fully restarted and out of safemode
 echo "***INFO: waiting for HDFS to exit safemode"
-sudo su hdfs --command "hdfs dfsadmin -safemode wait"
+sudo su hdfs --command "$HADOOP_BIN_PATH/hdfs dfsadmin -safemode wait"
 
 #====================================================
 # NOTE: These command must be done AFTER acls are 
 #       enabled and HDFS has been restarted
 echo "***INFO: Setting HDFS ACLs for snapshot scan support"
-sudo su hdfs --command "hdfs dfs -mkdir -p /hbase/archive"
+sudo su hdfs --command "$HADOOP_BIN_PATH/hdfs dfs -mkdir -p /hbase/archive"
 if [ $? != 0 ]; then
-   echo "***ERROR: (hdfs dfs -mkdir -p /hbase/archive) command failed"
+   echo "***ERROR: ($HADOOP_BIN_PATH/hdfs dfs -mkdir -p /hbase/archive) command failed"
    exit -1
 fi
-sudo su hdfs --command "hdfs dfs -chown hbase:hbase /hbase/archive"
+sudo su hdfs --command "$HADOOP_BIN_PATH/hdfs dfs -chown hbase:hbase /hbase/archive"
 if [ $? != 0 ]; then
-   echo "***ERROR: (hdfs dfs -chown hbase:hbase /hbase/archive) command failed"
+   echo "***ERROR: ($HADOOP_BIN_PATH/hdfs dfs -chown hbase:hbase /hbase/archive) command failed"
    exit -1
 fi
-sudo su hdfs --command "hdfs dfs -setfacl -R -m user:$TRAF_USER:rwx /hbase/archive"
+sudo su hdfs --command "$HADOOP_BIN_PATH/hdfs dfs -setfacl -R -m user:$TRAF_USER:rwx /hbase/archive"
 if [ $? != 0 ]; then
-   echo "***ERROR: (hdfs dfs -setfacl -R -m user:$TRAF_USER:rwx /hbase/archive) command failed"
+   echo "***ERROR: ($HADOOP_BIN_PATH/hdfs dfs -setfacl -R -m user:$TRAF_USER:rwx /hbase/archive) command failed"
    exit -1
 fi
-sudo su hdfs --command "hdfs dfs -setfacl -R -m default:user:$TRAF_USER:rwx /hbase/archive"
+sudo su hdfs --command "$HADOOP_BIN_PATH/hdfs dfs -setfacl -R -m default:user:$TRAF_USER:rwx /hbase/archive"
 if [ $? != 0 ]; then
-   echo "***ERROR: (hdfs dfs -setfacl -R -m default:user:$TRAF_USER:rwx /hbase/archive) command failed"
+   echo "***ERROR: ($HADOOP_BIN_PATH/hdfs dfs -setfacl -R -m default:user:$TRAF_USER:rwx /hbase/archive) command failed"
    exit -1
 fi
-sudo su hdfs --command "hdfs dfs -setfacl -R -m mask::rwx /hbase/archive"
+sudo su hdfs --command "$HADOOP_BIN_PATH/hdfs dfs -setfacl -R -m mask::rwx /hbase/archive"
 if [ $? != 0 ]; then
-   echo "***ERROR: (hdfs dfs -setfacl -R -m mask::rwx /hbase/archive) command failed"
+   echo "***ERROR: ($HADOOP_BIN_PATH/hdfs dfs -setfacl -R -m mask::rwx /hbase/archive) command failed"
    exit -1
 fi
+sudo su hdfs --command "$HADOOP_BIN_PATH/hdfs dfs -mkdir -p /hbase/archive/data"
+if [ $? != 0 ]; then
+   echo "***ERROR: ($HADOOP_BIN_PATH/hdfs dfs -mkdir -p /hbase/archive/data) command failed"
+   exit -1
+fi
+sudo su hdfs --command "$HADOOP_BIN_PATH/hdfs dfs -chown hbase:hbase /hbase/archive/data"
+if [ $? != 0 ]; then
+   echo "***ERROR: ($HADOOP_BIN_PATH/hdfs dfs -chown hbase:hbase /hbase/archive/data) command failed"
+   exit -1
+fi
+
+sudo su hdfs --command "$HADOOP_BIN_PATH/hdfs dfs -mkdir -p /hbase/archive/data/default"
+if [ $? != 0 ]; then
+   echo "***ERROR: ($HADOOP_BIN_PATH/hdfs dfs -mkdir -p /hbase/archive/data) command failed"
+   exit -1
+fi
+sudo su hdfs --command "$HADOOP_BIN_PATH/hdfs dfs -chown hbase:hbase /hbase/archive/data/default"
+if [ $? != 0 ]; then
+   echo "***ERROR: ($HADOOP_BIN_PATH/hdfs dfs -chown hbase:hbase /hbase/archive/data) command failed"
+   exit -1
+fi
+
 
 MODS_COMPLETE="Y"
 sudo chmod 777 $TRAF_CONFIG
@@ -364,4 +387,15 @@ sed -i '/MODS_COMPLETE\=/d' $TRAF_CONFIG
 echo "export MODS_COMPLETE=\"$MODS_COMPLETE\"" >> $TRAF_CONFIG
 sudo chmod 777 $TRAF_CONFIG
 source $TRAF_CONFIG
+
+TRAF_CONFIG_FILE="trafodion_config"
+TRAF_CONFIG_DIR="/etc/trafodion"
+
+if [ $node_count -ne 1 ]; then
+   cp $TRAF_CONFIG $LOCAL_WORKDIR
+   $TRAF_PDCP $LOCAL_WORKDIR/$TRAF_CONFIG_FILE $HOME
+   $TRAF_PDSH sudo mkdir -p $TRAF_CONFIG_DIR
+   $TRAF_PDSH sudo cp $HOME/$TRAF_CONFIG_FILE $TRAF_CONFIG_DIR
+   $TRAF_PDSH sudo chmod 777 $TRAF_CONFIG
+fi
 
diff --git a/install/installer/traf_config_check b/install/installer/traf_config_check
--- a/install/installer/traf_config_check
+++ b/install/installer/traf_config_check
@@ -222,8 +222,135 @@ fi
 source $TRAF_CONFIG
 }
 
-function checkJavaVersion {
+function checkManageNodeList {
 
+if [[ -z $MANAGE_NODES ]]; then
+   errorFound=1
+   echo "MANAGE NODE LIST" >> $ERROR_LOG
+   echo "***ERROR: MANAGE_NODES variable not set in config file." >> $ERROR_LOG
+else
+
+   ERROR_NODES=""
+   NODES=""
+
+   for node in $MANAGE_NODES
+   do
+      newNode=$(ssh -q -n $node hostname)
+
+      if [[ $? -ne "0" ]]; then
+         errorFound=1
+          echo "MANAGE NODE LIST" >> $ERROR_LOG
+         echo "***ERROR: Could not ssh to $node." >> $ERROR_LOG
+         echo "***ERROR: Please check node names for typos" >> $ERROR_LOG
+         majorErrorFound
+      fi
+
+      nodeName=$(echo $newNode | sed 's/[^a-zA-Z0-9\ \.\-]//g')
+
+      if [[ "$nodeName" != "$newNode" ]]; then
+         errorFound=1
+         echo "MANAGE NODE LIST" >> $ERROR_LOG
+         echo "***ERROR: Nodes are not named properly." >> $ERROR_LOG
+         echo "***ERROR: Nodes can have no special characters other than '-' and '.'" >> $ERROR_LOG
+      fi
+
+      if [[ "$newNode" =~ ^([0-9]{1,3})[.]([0-9]{1,3})[.]([0-9]{1,3})[.]([0-9]{1,3})$ ]]; then
+         errorFound=1
+          echo "MANAGE NODE LIST" >> $ERROR_LOG
+         echo "***ERROR: Nodes are not named properly." >> $ERROR_LOG
+         echo "***ERROR: IP addresses are not supported. Please use node names." >> $ERROR_LOG
+      fi
+
+      #Testing sudo access on all nodes
+      ssh -q -n $newNode sudo echo "***INFO: Testing sudo access on node $newNode"
+      if [ $? -ne "0" ]; then
+         error=1
+         ERROR_NODES="$ERROR_NODES $newNode"
+      fi
+      NODES="$NODES $newNode"
+   done
+
+   NODE_LIST=$NODES
+ if [[ $error == "1" ]]; then
+      errorFound=1
+       echo "MANAGE NODE LIST" >> $ERROR_LOG
+      echo "***ERROR: $ERROR_NODES does not have sudo access." >> $ERROR_LOG
+      echo "***ERROR: Must have sudo access on all nodes." >> $ERROR_LOG
+   fi
+
+
+   for node in $MANAGE_NODES
+   do
+      ssh -q -n $node echo "***INFO: Testing ssh on $node"
+      if [[ $? -ne "0" ]]; then
+         error=1
+         ERROR_NODES="$ERROR_NODES $node"
+      fi
+   done
+
+   if [[ $error == "1" ]]; then
+      errorFound=1
+      echo "TRAFODION NODE LIST" >> $ERROR_LOG
+      echo "***ERROR: Could not ssh to $ERROR_NODES." >> $ERROR_LOG
+      echo "***ERROR: Check permissions and known hosts files." >> $ERROR_LOG
+   fi
+
+
+   sudo chmod 777 $TRAF_CONFIG
+   sed -i '/MANAGE_NODES\=/d' $TRAF_CONFIG
+   echo "export MANAGE_NODES=\"$MANAGE_NODES\"" >> $TRAF_CONFIG
+   sudo chmod 777 $TRAF_CONFIG
+
+   manage_node_count=$(echo $MANAGE_NODES | wc -w)
+
+   sudo chmod 777 $TRAF_CONFIG
+   sed -i '/manage_node_count\=/d' $TRAF_CONFIG
+   echo "export manage_node_count=\"$manage_node_count\"" >> $TRAF_CONFIG
+   sudo chmod 777 $TRAF_CONFIG
+   
+
+   MY_MANAGE_NODES=""
+
+   for node in $MANAGE_NODES
+   do
+      MY_MANAGE_NODES="$MY_MANAGE_NODES -w $node"
+   done
+
+   sudo chmod 777 $TRAF_CONFIG
+   sed -i '/MY_MANAGE_NODES\=/d' $TRAF_CONFIG
+   echo "export MY_MANAGE_NODES=\"$MY_MANAGE_NODES\"" >> $TRAF_CONFIG
+   sudo chmod 777 $TRAF_CONFIG
+
+fi
+source $TRAF_CONFIG
+}
+
+function createAllNodes {
+
+ALL_NODE_LIST="$NODE_LIST $MANAGE_NODES"
+
+sudo chmod 777 $TRAF_CONFIG
+sed -i '/ALL_NODE_LIST\=/d' $TRAF_CONFIG
+echo "export ALL_NODE_LIST=\"$ALL_NODE_LIST\"" >> $TRAF_CONFIG
+sudo chmod 777 $TRAF_CONFIG
+
+all_node_count=$(echo $ALL_NODE_LIST | wc -w)
+
+sudo chmod 777 $TRAF_CONFIG
+sed -i '/all_node_count\=/d' $TRAF_CONFIG
+echo "export all_node_count=\"$all_node_count\"" >> $TRAF_CONFIG
+sudo chmod 777 $TRAF_CONFIG
+
+ALL_NODES="$MY_MANAGE_NODES $MY_NODES"
+
+sudo chmod 777 $TRAF_CONFIG
+sed -i '/ALL_NODES\=/d' $TRAF_CONFIG
+echo "export ALL_NODES=\"$ALL_NODES\"" >> $TRAF_CONFIG
+sudo chmod 777 $TRAF_CONFIG
+
+}
+
+function checkJavaVersion {
 if [[ -z "$JAVA_HOME" ]]; then
    errorFound=1
    echo "JAVA HOME" >> $ERROR_LOG
@@ -363,21 +490,20 @@ if [[ -z "$URL" ]]; then
    echo "***ERROR: Hadoop URL variable not set in config file."
    majorErrorFound  
 else
-   validURL=$(curl -s --head $URL | head -n 1 | grep "OK" | wc -l)
+   validURL=$(curl -k -s --head $URL | head -n 1 | grep "OK" | wc -l)
 
    if [[ $validURL -ne "1" ]]; then
       errorFound=1
       echo "HADOOP URL" >> $ERROR_LOG
-      echo "***ERROR: Could not access http://$URL" >> $ERROR_LOG
-      echo "***ERROR: Do not include 'http or https'" >> $ERROR_LOG
+      echo "***ERROR: Could not access $URL" >> $ERROR_LOG
       echo "***ERROR: Check that URL and port are correct or if $HADOOP_TYPE is up" >> $ERROR_LOG
       majorErrorFound
    fi
 
-   hadoopVersion=$(curl -su $ADMIN:$PASSWORD http://$URL/api/v1/clusters | grep version | grep -c CDH)
+   hadoopVersion=$(curl -k -su $ADMIN:$PASSWORD $URL/api/v1/clusters | grep version | grep -c CDH)
 
    if [[ $hadoopVersion -ne "1" ]]; then
-      hadoopVersion=$(curl -su $ADMIN:$PASSWORD http://$URL/api/v1/clusters | grep version | grep -c HDP)
+      hadoopVersion=$(curl -k -su $ADMIN:$PASSWORD $URL/api/v1/clusters | grep version | grep -c HDP)
       if [[ $hadoopVersion -ne "1" ]]; then
          errorFound=1
          echo "HADOOP URL" >> $ERROR_LOG
@@ -396,14 +522,14 @@ else
    sudo chmod 777 $TRAF_CONFIG
    source $TRAF_CONFIG
 
-   temp=$(curl -su $ADMIN:$PASSWORD http://$URL/api/v1/clusters |grep name | sed -e 's@[,]@@'g | sed 's/^[^\:]* ://')
+   temp=$(curl -k -su $ADMIN:$PASSWORD $URL/api/v1/clusters |grep name | sed -e 's@[,]@@'g | sed 's/^[^\:]* ://')
    CLUSTER_NAME=$(echo $temp | sed -e 's/^"//' -e 's/"$//')
    CLUSTER_NAME=${CLUSTER_NAME// /%20}
 
    if [ -z $CLUSTER_NAME ]; then
       errorFound=1
       echo "HADOOP URL" >> $ERROR_LOG
-      echo "***ERROR: Could not access http://$URL" >> $ERROR_LOG
+      echo "***ERROR: Could not access $URL" >> $ERROR_LOG
       echo "***ERROR: Check URL and port are correct or if $hadoop_type is up." >> $ERROR_LOG
       majorErrorFound
    fi
@@ -415,9 +541,10 @@ else
    source $TRAF_CONFIG
 
    if [[ $node_count -ne 1 ]]; then
+      nameOfInstallNode=$(hostname -s)
       sudo chmod 777 $TRAF_CONFIG
       sed -i '/CLUSTERNAME\=/d' $TRAF_CONFIG
-      echo "export CLUSTERNAME=\"$CLUSTER_NAME\"" >> $TRAF_CONFIG
+      echo "export CLUSTERNAME=\"$nameOfInstallNode\"" >> $TRAF_CONFIG
       sudo chmod 777 $TRAF_CONFIG
       source $TRAF_CONFIG
    fi
@@ -471,7 +598,7 @@ done
 
 function checkRoleGroups {
 
-   regionGroup1=$(curl -su $ADMIN:$PASSWORD http://$URL/api/v10/clusters/$CLUSTER_NAME/services/hbase/roleConfigGroups | grep displayName | grep "RegionServer Group 1" | wc -l)
+   regionGroup1=$(curl -k -su $ADMIN:$PASSWORD $URL/api/v10/clusters/$CLUSTER_NAME/services/hbase/roleConfigGroups | grep displayName | grep "RegionServer Group 1" | wc -l)
 
    if [[ $regionGroup1 -ge "1" ]]; then
       errorFound=1
@@ -500,8 +627,8 @@ if [[ $CDH_5_3_HDP_2_2_SUPPORT == "N" ]]; then
          fi
       fi
    else
-      versionInstalled=$(ssh -q -n $node grep "Version" hbaseVersion.txt | sed 's/,.*//' | sed 's/.*\-//' | grep cdh5.[0-1].* | wc -l)
-      nameOfVersion=$(ssh -q -n $node grep "Version" hbaseVersion.txt | sed 's/,.*//' | sed 's/.*\-//' | grep cdh5.[0-1].*)
+      versionInstalled=$(ssh -q -n $node grep "Version" $HOME/hbaseVersion.txt | sed 's/,.*//' | sed 's/.*\-//' | grep cdh5.[0-1].* | wc -l)
+      nameOfVersion=$(ssh -q -n $node grep "Version" $HOME/hbaseVersion.txt | sed 's/,.*//' | sed 's/.*\-//' | grep cdh5.[0-1].*)
       if [[ $versionInstalled -eq "0" ]]; then
          errorFound=1
          echo "HADOOP VERSION" >> $ERROR_LOG
@@ -511,10 +638,10 @@ if [[ $CDH_5_3_HDP_2_2_SUPPORT == "N" ]]; then
       fi
    fi
 else
-   nameOfVersion=$(ssh -q -n $node grep "Version" hbaseVersion.txt | sed 's/,.*//' | sed 's/.*\-//' | grep cdh5.[2-3].*)
+   nameOfVersion=$(ssh -q -n $node grep "Version" $HOME/hbaseVersion.txt | sed 's/,.*//' | sed 's/.*\-//' | grep cdh5.[2-3].*)
    #Check that Cloudera 5.[n>3].* is not installed.
    if [[ -z $nameOfVersion ]]; then
-      versionInstalled=$(ssh -q -n $node grep "Version" hbaseVersion.txt | sed 's/,.*//' | sed 's/.*\-//' | grep cdh[4-6].[0-9].* | wc -l)
+      versionInstalled=$(ssh -q -n $node grep "Version" $HOME/hbaseVersion.txt | sed 's/,.*//' | sed 's/.*\-//' | grep cdh[4-6].[0-9].* | wc -l)
        if [[ $versionInstalled -gt "0" ]]; then
           errorFound=1
           echo "HADOOP VERSION" >> $ERROR_LOG
@@ -700,8 +827,8 @@ fi
 
 function checkHadoopSupport {
 
-if [[ -z $TRAF_BUILD ]]; then
-   TRAF_BUILD=$(tar -tf $TRAF_PACKAGE | grep "trafodion_server")
+if [[ -z $TRAF_BUILD ]] || [[ ! -e $TRAF_BUILD ]] ; then
+   TRAF_BUILD=$(tar -tf $TRAF_PACKAGE | grep "trafodion_.*server")
    tar -xzf $TRAF_PACKAGE --directory $LOCAL_WORKDIR
    TRAF_BUILD_PATH=$LOCAL_WORKDIR/$TRAF_BUILD
 else
@@ -769,6 +896,12 @@ checkTrafPassword
 
 checkNodeList
 
+if [[ $MANAGE_ENABLED == "Y" ]]; then
+   checkManageNodeList
+fi
+
+createAllNodes
+
 checkJavaVersion
 
 checkHomeDir
@@ -794,3 +927,4 @@ checkDCS
 checkLDAP
 
 majorErrorFound
+
diff --git a/install/installer/traf_hortonworks_mods98 b/install/installer/traf_hortonworks_mods98
--- a/install/installer/traf_hortonworks_mods98
+++ b/install/installer/traf_hortonworks_mods98
@@ -66,7 +66,9 @@ else
     echo "***ERROR: unable to determine Hadoop's java version"
     exit -1
 fi
+
 traf_util_jar="trafodion-utility-${TRAF_VERSION}.jar"
+
 
 # The permissions the Trafodion build process creates on the hbase-trx jar
 # files does not work well with the installation process so we change them
@@ -93,9 +95,8 @@ if [ $node_count -ne 1 ]; then
     cp $UNTAR_DIR/export/lib/$traf_util_jar $LOCAL_WORKDIR
     $PDCP $MY_HADOOP_NODES $LOCAL_WORKDIR/$hbase_trx_jar $LOCAL_WORKDIR
     $PDCP $MY_HADOOP_NODES $LOCAL_WORKDIR/$traf_util_jar $LOCAL_WORKDIR
-
-    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo cp $LOCAL_WORKDIR/$hbase_trx_jar $HADOOP_PATH
     $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo cp $LOCAL_WORKDIR/$traf_util_jar $HADOOP_PATH
+    $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo cp $LOCAL_WORKDIR/$hbase_trx_jar $HADOOP_PATH
     $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo chmod 644 $HADOOP_PATH/$hbase_trx_jar
     $PDSH $MY_HADOOP_NODES $PDSH_SSH_CMD sudo chmod 644 $HADOOP_PATH/$traf_util_jar
 
@@ -113,7 +114,6 @@ else
     ssh -q -n $node sudo chmod 777 $TRAF_WORKDIR
     scp -q $UNTAR_DIR/export/lib/$hbase_trx_jar $(whoami)@$node:$TRAF_WORKDIR
     scp -q $UNTAR_DIR/export/lib/$traf_util_jar $(whoami)@$node:$TRAF_WORKDIR
-
     ssh -q -n $node sudo cp $TRAF_WORKDIR/$hbase_trx_jar $HADOOP_PATH
     ssh -q -n $node sudo cp $TRAF_WORKDIR/$traf_util_jar $HADOOP_PATH
     ssh -q -n $node sudo chmod 644 $HADOOP_PATH/$hbase_trx_jar
@@ -271,10 +271,10 @@ echo
 poll_time=30
 echo "***INFO: Restarting HBase to pick up config changes for Trafodion"
 echo "***INFO: Stopping HBase..."
-curl -u $ADMIN:$PASSWORD \
+curl -k -u $ADMIN:$PASSWORD \
     -H "X-Requested-By: Trafodion" \
     -X PUT -d '{"ServiceInfo": { "state" : "INSTALLED" }}' \
-    http://$URL/api/v1/clusters/$CLUSTER_NAME/services/HBASE > $TRAF_WORKDIR/traf_hbase_restart_temp
+    $URL/api/v1/clusters/$CLUSTER_NAME/services/HBASE > $TRAF_WORKDIR/traf_hbase_restart_temp
 
 if [ $? != 0 ]; then 
    echo "***ERROR: Unable to stop HBase"
@@ -298,8 +298,8 @@ echo "***DEBUG: Ambari command_id=$command_id"
 completed=0
 while [ $completed -eq 0 ]; do
     sleep $poll_time
-    curl -u $ADMIN:$PASSWORD \
-        http://$URL/api/v1/clusters/$CLUSTER_NAME/requests/$command_id \
+    curl -k -u $ADMIN:$PASSWORD \
+        $URL/api/v1/clusters/$CLUSTER_NAME/requests/$command_id \
         > $LOCAL_WORKDIR/hbase_restart_status_temp
     cat $LOCAL_WORKDIR/hbase_restart_status_temp
     echo "***INFO: ...polling every $poll_time seconds until HBase stop is completed."
@@ -313,10 +313,10 @@ echo "***INFO: HBase stop completed"
 #Stop Zookeeper
 
 echo "***INFO: Stopping Zookeeper..."
-curl --user $ADMIN:$PASSWORD \
+curl -k --user $ADMIN:$PASSWORD \
     -H "X-Requested-By: Trafodion" \
     -X PUT -d '{"ServiceInfo": { "state" : "INSTALLED" }}' \
-    http://$URL/api/v1/clusters/$CLUSTER_NAME/services/ZOOKEEPER > $TRAF_WORKDIR/traf_zoo_restart_temp
+    $URL/api/v1/clusters/$CLUSTER_NAME/services/ZOOKEEPER > $TRAF_WORKDIR/traf_zoo_restart_temp
 
 if [ $? != 0 ]; then
    echo "***ERROR: Unable to restart Zookeeper"
@@ -340,8 +340,8 @@ echo "***DEBUG: Ambari command_id=$command_id"
 completed=0
 while [ $completed -eq 0 ]; do
     sleep $poll_time
-    curl --user $ADMIN:$PASSWORD \
-        http://$URL/api/v1/clusters/$CLUSTER_NAME/requests/$command_id \
+    curl -k --user $ADMIN:$PASSWORD \
+        $URL/api/v1/clusters/$CLUSTER_NAME/requests/$command_id \
         > $LOCAL_WORKDIR/traf_zoo_restart_temp
     cat $LOCAL_WORKDIR/traf_zoo_restart_temp
     echo "***INFO: ...polling every $poll_time seconds until Zookeeper stop is completed."
@@ -354,10 +354,10 @@ done
 
 echo "***INFO: Restarting HDFS to pick up config changes for Trafodion"
 echo "***INFO: Stopping HDFS..."
-curl --user $ADMIN:$PASSWORD \
+curl -k --user $ADMIN:$PASSWORD \
     -H "X-Requested-By: Trafodion" \
     -X PUT -d '{"ServiceInfo": { "state" : "INSTALLED" }}' \
-    http://$URL/api/v1/clusters/$CLUSTER_NAME/services/HDFS > $TRAF_WORKDIR/traf_hdfs_restart_temp
+    $URL/api/v1/clusters/$CLUSTER_NAME/services/HDFS > $TRAF_WORKDIR/traf_hdfs_restart_temp
 
 if [ $? != 0 ]; then 
    echo "***ERROR: Unable to restart HDFS"
@@ -381,8 +381,8 @@ echo "***DEBUG: Ambari command_id=$command_id"
 completed=0
 while [ $completed -eq 0 ]; do
     sleep $poll_time
-    curl --user $ADMIN:$PASSWORD \
-        http://$URL/api/v1/clusters/$CLUSTER_NAME/requests/$command_id \
+    curl -k --user $ADMIN:$PASSWORD \
+        $URL/api/v1/clusters/$CLUSTER_NAME/requests/$command_id \
         > $LOCAL_WORKDIR/traf_hdfs_restart_temp
     cat $LOCAL_WORKDIR/traf_hdfs_restart_temp
     echo "***INFO: ...polling every $poll_time seconds until HDFS stop is completed."
@@ -391,10 +391,10 @@ while [ $completed -eq 0 ]; do
 done
 
 echo "***INFO: Starting HDFS..."
-curl --user $ADMIN:$PASSWORD \
+curl -k --user $ADMIN:$PASSWORD \
     -H "X-Requested-By: Trafodion" \
     -X PUT -d '{"ServiceInfo": { "state" : "STARTED" }}' \
-    http://$URL/api/v1/clusters/$CLUSTER_NAME/services/HDFS > $TRAF_WORKDIR/traf_hdfs_restart_temp
+    $URL/api/v1/clusters/$CLUSTER_NAME/services/HDFS > $TRAF_WORKDIR/traf_hdfs_restart_temp
 
 if [ $? != 0 ]; then
    echo "***ERROR: Unable to restart HDFS"
@@ -417,8 +417,8 @@ echo "***DEBUG: Ambari command_id=$command_id"
 completed=0
 while [ $completed -eq 0 ]; do
     sleep $poll_time
-    curl --user $ADMIN:$PASSWORD \
-        http://$URL/api/v1/clusters/$CLUSTER_NAME/requests/$command_id \
+    curl -k --user $ADMIN:$PASSWORD \
+        $URL/api/v1/clusters/$CLUSTER_NAME/requests/$command_id \
         > $LOCAL_WORKDIR/traf_hdfs_restart_temp
     cat $LOCAL_WORKDIR/traf_hdfs_restart_temp
     echo "***INFO: ...polling every $poll_time seconds until HDFS start is completed."
@@ -436,10 +436,10 @@ sudo su hdfs --command "hdfs dfsadmin -safemode wait"
 # Start Zookeeper to pick up all the changes just made
 
 echo "***INFO: Starting Zookeeper..."
-curl --user $ADMIN:$PASSWORD \
+curl -k --user $ADMIN:$PASSWORD \
     -H "X-Requested-By: Trafodion" \
     -X PUT -d '{"ServiceInfo": { "state" : "STARTED" }}' \
-    http://$URL/api/v1/clusters/$CLUSTER_NAME/services/ZOOKEEPER > $TRAF_WORKDIR/traf_zoo_restart_temp
+    $URL/api/v1/clusters/$CLUSTER_NAME/services/ZOOKEEPER > $TRAF_WORKDIR/traf_zoo_restart_temp
 
 if [ $? != 0 ]; then
    echo "***ERROR: Unable to restart Zookeeper"
@@ -462,8 +462,8 @@ echo "***DEBUG: Ambari command_id=$command_id"
 completed=0
 while [ $completed -eq 0 ]; do
     sleep $poll_time
-    curl --user $ADMIN:$PASSWORD \
-        http://$URL/api/v1/clusters/$CLUSTER_NAME/requests/$command_id \
+    curl -k --user $ADMIN:$PASSWORD \
+        $URL/api/v1/clusters/$CLUSTER_NAME/requests/$command_id \
         > $LOCAL_WORKDIR/traf_zoo_restart_temp
     cat $LOCAL_WORKDIR/traf_zoo_restart_temp
     echo "***INFO: ...polling every $poll_time seconds until Zookeeper start is completed."
@@ -478,10 +478,10 @@ echo "***INFO: Zookeeper start completed"
 
 echo "***INFO: Restarting HBase to pick up config changes for Trafodion"
 echo "***INFO: Starting HBase..."
-curl -u $ADMIN:$PASSWORD \
+curl -k -u $ADMIN:$PASSWORD \
     -H "X-Requested-By: Trafodion" \
     -X PUT -d '{"ServiceInfo": { "state" : "STARTED" }}' \
-    http://$URL/api/v1/clusters/$CLUSTER_NAME/services/HBASE > $TRAF_WORKDIR/traf_hbase_restart_temp
+    $URL/api/v1/clusters/$CLUSTER_NAME/services/HBASE > $TRAF_WORKDIR/traf_hbase_restart_temp
 
 if [ $? != 0 ]; then
    echo "***ERROR: Unable to restart HBase"
@@ -504,8 +504,8 @@ echo "***DEBUG: Ambari command_id=$command_id"
 completed=0
 while [ $completed -eq 0 ]; do
     sleep $poll_time
-    curl -u $ADMIN:$PASSWORD \
-        http://$URL/api/v1/clusters/$CLUSTER_NAME/requests/$command_id \
+    curl -k -u $ADMIN:$PASSWORD \
+        $URL/api/v1/clusters/$CLUSTER_NAME/requests/$command_id \
         > $LOCAL_WORKDIR/hbase_restart_status_temp
     cat $LOCAL_WORKDIR/hbase_restart_status_temp
     echo "***INFO: ...polling every $poll_time seconds until HBase start is completed."
@@ -545,6 +545,32 @@ if [ $? != 0 ]; then
    exit -1
 fi
 
+ssh -q -n $AMBARI_HOST 'sudo su hdfs --command "hdfs dfs -mkdir -p /apps/hbase/data/archive/data"'
+if [ $? != 0 ]; then
+   echo "***ERROR: (hdfs dfs -mkdir -p /apps/hbase/data/archive/data) command failed"
+   exit -1
+fi
+
+ssh -q -n $AMBARI_HOST 'sudo su hdfs --command "hdfs dfs -chown hbase:hdfs /apps/hbase/data/archive/data"'
+if [ $? != 0 ]; then
+   echo "***ERROR: (hdfs dfs -chown hbase:hdfs /apps/hbase/data/archive/data) command failed"
+   exit -1
+fi
+
+ssh -q -n $AMBARI_HOST 'sudo su hdfs --command "hdfs dfs -mkdir -p /apps/hbase/data/archive/data/default"'
+if [ $? != 0 ]; then
+   echo "***ERROR: (hdfs dfs -mkdir -p /apps/hbase/data/archive/data/default) command failed"
+   exit -1
+fi
+
+ssh -q -n $AMBARI_HOST 'sudo su hdfs --command "hdfs dfs -chown hbase:hdfs /apps/hbase/data/archive/data/default"'
+if [ $? != 0 ]; then
+   echo "***ERROR: (hdfs dfs -chown hbase:hdfs /apps/hbase/data/archive/data/default) command failed"
+   exit -1
+fi
+
+
+
 
 # clean up files generated by Ambari's config.sh script
 ssh -q -n $AMBARI_HOST 'rm $HOME/doSet_version*'
@@ -555,4 +581,15 @@ sed -i '/MODS_COMPLETE\=/d' $TRAF_CONFIG
 echo "export MODS_COMPLETE=\"$MODS_COMPLETE\"" >> $TRAF_CONFIG
 sudo chmod 777 $TRAF_CONFIG
 source $TRAF_CONFIG
+
+TRAF_CONFIG="trafodion_config"
+TRAF_CONFIG_DIR="/etc/trafodion"
+
+if [ $node_count -ne 1 ]; then
+   cp $TRAF_CONFIG $LOCAL_WORKDIR
+   $TRAF_PDCP $LOCAL_WORKDIR/$TRAF_CONFIG_FILE $HOME
+   $TRAF_PDSH sudo mkdir -p $TRAF_CONFIG_DIR
+   $TRAF_PDSH sudo cp $HOME/$TRAF_CONFIG_FILE $TRAF_CONFIG_DIR
+   $TRAF_PDSH sudo chmod 777 $TRAF_CONFIG
+fi
 
