[TRAFODION-2654] Change the location of trafodion-site.xml from $TRAF_HOME/etc to config [TRAFODION-2653] Sort operator loops at times
All HBase client connections from Trafodion uses Trafodion configuration
concept. Any client side property can now be set in trafodion-site.xml.

The scratch files are now open in blocking mode. Hence any scratch file
operation shouldn't return EAGAIN.

The internal table TDDL of table is now created without any table
coprocessors attached to it.

diff --git a/core/sqf/sql/scripts/sqgen b/core/sqf/sql/scripts/sqgen
--- a/core/sqf/sql/scripts/sqgen
+++ b/core/sqf/sql/scripts/sqgen
@@ -28,10 +28,9 @@ function Usage {
     echo
     echo $script_name generates various Trafodion files in the $TRAF_HOME/sql/scripts directory.
     echo
-    echo "Usage: $script_name [ -? | -h ] [<sqconfig_filename>]"
-    echo "  -?    Help"
+    echo "Usage: $script_name {-ft | -perf | [sqconfig_filename] | -h}"
     echo "  -h    Help"
-    echo "  <sqconfig_filename> Name of the SQ config file (in $TRAF_HOME/sql/scripts directory)(defaults to 'sqconfig')"
+    echo "  [sqconfig_filename] Name of the SQ config file (in $TRAF_HOME/sql/scripts directory)(defaults to 'sqconfig')"
     echo
     exit 1;
 }
@@ -75,7 +74,6 @@ function GetSQcnfg {
 FT_FLAG=1
 PERF_FLAG=0
 SQCONFIG_FILE=sqconfig
-SQCONFIG_DB_FILE=sqconfig.db
 
 if [ -z $TRAF_HOME ]; then
     echo
@@ -121,38 +119,15 @@ cd $TRAF_HOME/sql/scripts
 
 # Check to make sure this is a real cluster
 if  [[ -n "$node_count" ]] && [[ "$node_count" -gt "1" ]]; then 
-    # The configuration database can only be created the first time.
-    # Since nodes can be added and deleted through the 'shell node add/delete'
-    # commands, the 'sqconfig' node section may not reflect the current node
-    # configured. The 'sqregen' script can be used to update the SQCONFIG_FILE
-    # node section to reflect the current node configuration stored in
-    # the SQCONFIG_DB_FILE.
-    echo "Checking for the configuration file ($SQCONFIG_DB_FILE)."
-    if [ -f $SQCONFIG_DB_FILE ]; then
-        echo
-        echo "The configuration file ($SQCONFIG_DB_FILE) exists."
-        echo "Use the 'sqshell node add/delete' commands to change the node membership in the configuration database."
-        echo "Use the 'sqshell persist add/delete' commands to change the persist object configuration in the configuration database."
-        echo "Use the 'sqregen -node' script to update the $SQCONFIG_FILE 'node' section with the"
-        echo "current node membership in the configuration database."
-        echo "Use the 'sqregen -persist' script to update the $SQCONFIG_FILE 'persist' section with the"
-        echo "current persist configuration stored in the configuration database."
-        exit 1
-    fi
 
     GetSQcnfg
+
 else
-    echo
-    echo "Workstation environment - Not a clustered environment"
-    if [ -f $SQCONFIG_DB_FILE ]; then
-        echo
-        echo "The configuration file ($SQCONFIG_DB_FILE) was previously created."
-        echo "Removing and re-creating $SQCONFIG_DB_FILE!"
-        rm -f $SQCONFIG_DB_FILE
-    fi
+   echo "Workstation environment - Not a clustered environment"
 fi
 
-# Assume option is SQCONFIG_FILE
+# -ft command line option indicates fault tolerance,
+# otherwise we assume option is SQCONFIG_FILE
 while [ $# != 0 ]
   do
     flag="$1"
@@ -172,6 +147,7 @@ mkdir -p $MPI_TMPDIR
 # mkdir a dir for CBF data used by SQL IUS feature
 mkdir -p $HOME/cbfs
 
+#If pdsh exists
 if  [[ -n "$node_count" ]] && [[ "$node_count" -gt "1" ]]; then    
     echo
     echo "Creating directories on cluster nodes"
@@ -191,6 +167,7 @@ if  [[ -n "$node_count" ]] && [[ "$node_count" -gt "1" ]]; then
 fi
 
 SQSCRIPT_FILE=./gomon
+SQCLUSTERCONF_FILE=$MPI_TMPDIR/cluster.conf
 SQESPENV_FILE=$TRAF_HOME/sql/scripts/tdm_arkesp.env
 
 echo
@@ -204,34 +181,20 @@ else
     ./genms > $SQETC_DIR/ms.env
     lv_retcode=$?
     if [[ $lv_retcode != 0 ]]; then 
-        echo "Error $lv_retcode while executing genms. Exiting..."
-        exit $lv_retcode
+	echo "Error $lv_retcode while executing genms. Exiting..."
+	exit $lv_retcode
     fi
 fi
 
 ./gensqstatem2lenv > $SQETC_DIR/sqstatem2l.env
 
-if [ -f $SQETC_DIR/trafodion-site.xml ]; then
-    echo "Trafodion customization file $SQETC_DIR/trafodion-site.xml exists."
-    echo "The file will not be copied."
-    echo
-else
-    echo "Copying Trafodion customization file: $SQETC_DIR/trafodion-site.xml"
-    echo
-    cp ./trafodion-site.xml $SQETC_DIR
-    lv_retcode=$?
-    if [[ $lv_retcode != 0 ]]; then 
-	echo "Error $lv_retcode while copying Exiting..."
-	exit $lv_retcode
-    fi
-fi
-
 # Create configuration database tables
-sqlite3 -init createConfigDb $SQCONFIG_DB_FILE <<eof 
+rm -f sqconfig.db
+sqlite3 -init createConfigDb sqconfig.db <<eof 
 .quit
 eof
 
-./gensq.pl $SQSCRIPT_FILE `hostname` $FT_FLAG $PERF_FLAG $SQCONFIG_FILE $TRAF_HOME/sql/scripts/sqconfig.persist
+./gensq.pl $SQCONFIG_FILE $SQSCRIPT_FILE $SQCLUSTERCONF_FILE `hostname` $FT_FLAG $PERF_FLAG
 sq_stat=$?
 if [[ $sq_stat != 0 ]]; then 
     exit $sq_stat;
@@ -267,13 +230,16 @@ if  [[ -n "$node_count" ]] && [[ "$node_count" -gt "1" ]]; then
     echo
     echo "Copying the generated files to all the nodes in the cluster"
     echo
+    echo "Copying $SQCLUSTERCONF_FILE to $MPI_TMPDIR of all the nodes"
+    echo "$PDCP -w ${ExNodeList[@]} -x `uname -n` $SQCLUSTERCONF_FILE $MPI_TMPDIR"
+    $PDCP -w ${ExNodeList[@]} -x `uname -n` $SQCLUSTERCONF_FILE $MPI_TMPDIR
+
+
+    echo
     echo "Copying $SQETC_DIR/ms.env to $SQETC_DIR of all the nodes"
     echo "$PDCP -w ${ExNodeList[@]} -x `uname -n` $SQETC_DIR/ms.env   $SQETC_DIR "
     $PDCP -w ${ExNodeList[@]} -x `uname -n` $SQETC_DIR/ms.env   $SQETC_DIR
 
-    echo "Copying $SQETC_DIR/traf_coprocessor.properties to $SQETC_DIR of all the nodes"
-    echo "$PDCP -w ${ExNodeList[@]} -x `uname -n` $SQETC_DIR/traf_coprocessor.properties   $SQETC_DIR "
-    $PDCP -w ${ExNodeList[@]} -x `uname -n` $SQETC_DIR/traf_coprocessor.properties   $SQETC_DIR
 
     echo
     echo "Copying $SQETC_DIR/seamonster.env to $SQETC_DIR of all the nodes"
@@ -292,11 +258,11 @@ if  [[ -n "$node_count" ]] && [[ "$node_count" -gt "1" ]]; then
     echo
     echo "Copying rest of the generated files to $PWD"
 
-    echo "$PDCP -w ${ExNodeList[@]} -x `uname -n` sqconfig sqshell gomon.cold rmsstart rmsstop rmscheck.sql ssmpstart ssmpstop sscpstart sscpstop $PWD"
-    $PDCP -w ${ExNodeList[@]} -x `uname -n` sqconfig sqshell gomon.cold rmsstart rmsstop rmscheck.sql ssmpstart ssmpstop sscpstart sscpstop $PWD
+    echo "$PDCP -w ${ExNodeList[@]} -x `uname -n` sqconfig sqshell gomon.cold gomon.warm rmsstart rmsstop rmscheck.sql ssmpstart ssmpstop sscpstart sscpstop $PWD"
+    $PDCP -w ${ExNodeList[@]} -x `uname -n` sqconfig sqshell gomon.cold gomon.warm rmsstart rmsstop rmscheck.sql ssmpstart ssmpstop sscpstart sscpstop $PWD
 
-    echo "$PDCP -w ${ExNodeList[@]} -x `uname -n` $SQCONFIG_FILE $SQCONFIG_DB_FILE $PWD "
-    $PDCP -w ${ExNodeList[@]} -x `uname -n` $SQCONFIG_FILE $SQCONFIG_DB_FILE $PWD
+    echo "$PDCP -w ${ExNodeList[@]} -x `uname -n` $SQCONFIG_FILE sqconfig.db $PWD "
+    $PDCP -w ${ExNodeList[@]} -x `uname -n` $SQCONFIG_FILE sqconfig.db $PWD
 
 
     echo
