Do not make again before MAKE CLEAN

diff --git a/core/sqf/src/seatrans/tm/hbasetmlib2/Makefile b/core/sqf/src/seatrans/tm/hbasetmlib2/Makefile
--- a/core/sqf/src/seatrans/tm/hbasetmlib2/Makefile
+++ b/core/sqf/src/seatrans/tm/hbasetmlib2/Makefile
@@ -64,14 +64,14 @@ endif
 all:  $(PROGS) mavenbuild
 
 mavenbuild:
-	# create a jar manifest file with the correct version information
-	mkdir -p src/main/resources
-	$(TRAF_HOME)/export/include/SCMBuildJava.sh 1.0.1 >src/main/resources/trafodion-dtm.jar.mf
-	# run maven
-	set -o pipefail; $(MAVEN) package -DskipTests | tee maven_build.log | grep -e '\[INFO\] Building' -e '\[INFO\] BUILD SUCCESS' -e 'ERROR'
-	set -o pipefail; $(MAVEN) -f pom.xml.apache package -DskipTests | tee maven_build_apache.log | grep -e '\[INFO\] Building' -e '\[INFO\] BUILD SUCCESS' -e 'ERROR'
-	set -o pipefail; $(MAVEN) -f pom.xml.hdp package -DskipTests | tee maven_build_hdp.log | grep -e '\[INFO\] Building' -e '\[INFO\] BUILD SUCCESS' -e 'ERROR'	
-	cp -pf target/trafodion-dtm-*.jar $(TRAF_HOME)/export/lib
+	@if [ ! -f target/*.jar ]; then \
+		mkdir -p src/main/resources ; \
+		$(TRAF_HOME)/export/include/SCMBuildJava.sh 1.0.1 >src/main/resources/trafodion-dtm.jar.mf ; \
+		set -o pipefail; $(MAVEN) package -DskipTests | tee maven_build.log | grep -e '\[INFO\] Building' -e '\[INFO\] BUILD SUCCESS' -e 'ERROR' ; \
+		set -o pipefail; $(MAVEN) -f pom.xml.apache package -DskipTests | tee maven_build_apache.log | grep -e '\[INFO\] Building' -e '\[INFO\] BUILD SUCCESS' -e 'ERROR' ; \
+		set -o pipefail; $(MAVEN) -f pom.xml.hdp package -DskipTests | tee maven_build_hdp.log | grep -e '\[INFO\] Building' -e '\[INFO\] BUILD SUCCESS' -e 'ERROR' ; \
+		cp -pf target/trafodion-dtm-*.jar $(TRAF_HOME)/export/lib ; \
+	fi
 
 $(LIBEXPDIR)/libshbasetmlib.so: $(LIBSTMOBJS)
 	$(CXX) $(DTMOBJS) $(LNK_FLGS) $(LIBTMB) -shared -o $@ $(LIBSTMOBJS)
@@ -100,7 +100,9 @@ clean:
 	$(RM) *.gcda *.gcno *.gcov
 	$(RM) -f  $(OUTDIR)/*.o
 	$(RM) -rf $(TRAF_HOME)/export/lib/trafodion-dtm-*.jar
-	-$(MAVEN) -f pom.xml clean
+	-@if [ -d target ]; then \
+		$(MAVEN) -f pom.xml clean ; \
+	fi
 
 cleanall: clean
 	$(RM) -rf $(BUILD_PLAT)
