Fix bug 1351655 and adding wrappers for uninstall
Fix for bug 1351655, script will look if cloudera has been installed and
skip the Cloudera install steps.

Wrapper scripts added for all uninstall scripts. Fixes for single node
uninstall also included.

Edit 1: Small changes suggested by reviewers.

Edit 2: Adding in other fixes.
trafodion_mods: Fix for bug 1353606
trafodion_setup: Copying trafodion_server* to trafodion_build.tgz and
putting into workding directory to be used by trafodion_mods.
traf_ambari_setup: Checking to see if Hortonworks/Ambari has previously
been installed.

Edit 3: Typo fix.

All uninstall scripts: Adding full path names for scripts.
Change-Id: Iab4584e29250ddc149e239c1269760e8fcfd83e3

diff --git a/installer/traf_ambari_setup b/installer/traf_ambari_setup
--- a/installer/traf_ambari_setup
+++ b/installer/traf_ambari_setup
@@ -143,33 +143,36 @@ echo "Home directory: $HOME_DIR" >> $SETUP_LOG
 echo >> $SETUP_LOG
 
 #==============================================
+if [[ $AMBARI -eq 0 ]]; then
+   echo "***INFO: Installing Hortonworks/Ambari, will need browser access to complete" | tee -a $SETUP_LOG
 
-echo "***INFO: Installing Hortonworks/Ambari, will need browser access to complete" | tee -a $SETUP_LOG
+   wget http://public-repo-1.hortonworks.com/ambari/centos6/1.x/updates/1.5.1/ambari.repo
 
-wget http://public-repo-1.hortonworks.com/ambari/centos6/1.x/updates/1.5.1/ambari.repo
+   if [ $? -ne 0 ]; then
+      echo "***ERROR: Time out error. Please check http_proxy settings." | tee -a $SETUP_LOG
+      echo "***ERROR: Exiting..." | tee -a $SETUP_LOG
+      echo
+      exit -1
+   fi
 
-if [ $? -ne 0 ]; then
-   echo "****ERROR: Time our error. Please check http_proxy settings." | tee -a $SETUP_LOG
-   echo "***ERROR: Exiting..." | tee -a $SETUP_LOG
+   sudo cp ambari.repo /etc/yum.repos.d
+   sudo yum --assumeyes install ambari-server
+   sudo ambari-server setup
+   sudo ambari-server start
+
+   if [ $? -ne 0 ]; then
+      echo "***ERROR: Error while installing Hortonworks/Ambari" | tee -a $SETUP_LOG
+      echo "***ERROR: Exiting..." | tee -a $SETUP_LOG
+      echo
+      exit -1
+   fi
+
+   echo "***INFO: Complete Hortonworks/Ambari setup from http://localhost:8080" | tee -a $SETUP_LOG
+else
    echo
-   exit -1
+   echo "***INFO: Hortonworks/Ambari previously installed." | tee -a $SETUP_LOG
+
 fi
-
-sudo cp ambari.repo /etc/yum.repos.d
-sudo yum --assumeyes install ambari-server
-sudo ambari-server setup
-sudo ambari-server start
-
-if [ $? -ne 0 ]; then
-   echo "***ERROR: Error while installing Hortonworks/Ambari" | tee -a $SETUP_LOG
-   echo "***ERROR: Exiting..." | tee -a $SETUP_LOG
-   echo
-   exit -1
-fi
-
-
-echo "***INFO: Complete Hortonworks/Ambari setup from http://localhost:8080" | tee -a $SETUP_LOG
-
 #==============================================
 
 echo "***INFO: Running Trafodion Setup"
diff --git a/installer/traf_cloudera_setup b/installer/traf_cloudera_setup
--- a/installer/traf_cloudera_setup
+++ b/installer/traf_cloudera_setup
@@ -202,42 +202,48 @@ else
 fi
 
 #==============================================
+cloudera_installed=$(rpm -qa | grep cloudera | wc -l )
 
-echo "***INFO: Installing Cloudera, will need browser access to complete" | tee -a $SETUP_LOG
+if [[ $cloudera_installed -eq 0 ]]; then
 
-wget http://archive.cloudera.com/cm5/installer/latest/cloudera-manager-installer.bin
+   echo "***INFO: Installing Cloudera, will need browser access to complete" | tee -a $SETUP_LOG
 
-if [ $? -ne 0 ]; then
-   echo "****ERROR: Time our error. Please check http_proxy settings." | tee -a $SETUP_LOG
-   echo "***ERROR: Exiting..." | tee -a $SETUP_LOG
+   wget http://archive.cloudera.com/cm5/installer/latest/cloudera-manager-installer.bin
+
+   if [ $? -ne 0 ]; then
+      echo "****ERROR: Time our error. Please check http_proxy settings." | tee -a $SETUP_LOG
+      echo "***ERROR: Exiting..." | tee -a $SETUP_LOG
+      echo
+      exit -1
+   fi
+
+   wget http://archive.cloudera.com/cm5/redhat/6/x86_64/cm/5/RPMS/x86_64/oracle-j2sdk1.7-1.7.0+update55-2.x86_64.rpm
+
+   if [ $? -ne 0 ]; then
+      echo "****ERROR: Time our error. Please check http_proxy settings." | tee -a $SETUP_LOG
+      echo "***ERROR: Exiting..." | tee -a $SETUP_LOG
+      echo
+      exit -1
+   fi
+
+   sudo rpm -ivh oracle-j2sdk1.7-1.7.0+update55-2.x86_64.rpm 
+
+   chmod +x cloudera-manager-installer.bin
+
+   sudo ./cloudera-manager-installer.bin --i-agree-to-all-licenses --noreadme
+
+   if [ $? -ne 0 ]; then
+      echo "***ERROR: Error while installing Cloudera" | tee -a $SETUP_LOG
+      echo "***ERROR: Exiting..." | tee -a $SETUP_LOG
+      echo
+      exit -1
+   fi
+
+   echo "***INFO: Complete Cloudera setup from http://localhost:7180" | tee -a $SETUP_LOG 
+else
    echo
-   exit -1
+   echo "***INFO: Cloudera previously installed." | tee -a $SETUP_LOG
 fi
-
-wget http://archive.cloudera.com/cm5/redhat/6/x86_64/cm/5/RPMS/x86_64/oracle-j2sdk1.7-1.7.0+update55-2.x86_64.rpm
-
-if [ $? -ne 0 ]; then
-   echo "****ERROR: Time our error. Please check http_proxy settings." | tee -a $SETUP_LOG
-   echo "***ERROR: Exiting..." | tee -a $SETUP_LOG
-   echo
-   exit -1
-fi
-
-sudo rpm -ivh oracle-j2sdk1.7-1.7.0+update55-2.x86_64.rpm
-
-chmod +x cloudera-manager-installer.bin
-
-sudo ./cloudera-manager-installer.bin --i-agree-to-all-licenses --noreadme
-
-if [ $? -ne 0 ]; then
-   echo "***ERROR: Error while installing Cloudera" | tee -a $SETUP_LOG
-   echo "***ERROR: Exiting..." | tee -a $SETUP_LOG
-   echo
-   exit -1
-fi
-
-echo "**INFO: Complete Cloudera setup from http://localhost:7180" | tee -a $SETUP_LOG 
-
 #==============================================
 echo "***INFO: Running Trafodion Setup"
 if [[ $HBASE_TRX_JAR == "" ]]; then
diff --git a/installer/trafodion_setup b/installer/trafodion_setup
--- a/installer/trafodion_setup
+++ b/installer/trafodion_setup
@@ -29,6 +29,7 @@ typeset NODE_LIST="$HOSTNAME"
 typeset CLUSTERNAME="$HOSTNAME"
 typeset HBASE_TRX_JAR=""
 typeset HOME_DIR="/home"
+
 #==============================================
 
 function print_usage {
@@ -313,22 +314,27 @@ if [ $node_count -ne 1 ]; then
     done
 fi
 
-echo "***INFO: ... EPEL rpm"
-epel_rpm="epel-release-6-8.noarch.rpm"
-wget http://download.fedoraproject.org/pub/epel/6/x86_64/$epel_rpm
-if [ $? != 0 ]; then
-    echo "***ERROR: Can't download EPEL rpm $epel_rpm"
-    exit -1
-fi
-if [ $node_count -ne 1 ]; then
-    pdcp $MY_NODES $epel_rpm $TRAF_WORKDIR
-else
-    cp $epel_rpm $TRAF_WORKDIR
-fi 
-$TRAF_PDSH sudo rpm -Uvh $TRAF_WORKDIR/$epel_rpm 2>> $YUM_LOG >> $YUM_LOG
-if [ $? != 0 ]; then
-    echo "***ERROR: Can't install EPEL rpm $epel_rpm"
-    exit -1
+#Checking to see if epel package is installed. 
+EPEL_INSTALLED=$( rpm -qa | grep epel | wc -l)
+
+if [[ $EPEL_INSTALLED == 0 ]]; then
+   echo "***INFO: ... EPEL rpm"
+   epel_rpm="epel-release-6-8.noarch.rpm"
+   wget http://download.fedoraproject.org/pub/epel/6/x86_64/$epel_rpm
+   if [ $? != 0 ]; then
+      echo "***ERROR: Can't download EPEL rpm $epel_rpm"
+      exit -1
+   fi
+   if [ $node_count -ne 1 ]; then
+      pdcp $MY_NODES $epel_rpm $TRAF_WORKDIR
+   else
+      cp $epel_rpm $TRAF_WORKDIR
+   fi 
+   $TRAF_PDSH sudo rpm -Uvh $TRAF_WORKDIR/$epel_rpm 2>> $YUM_LOG >> $YUM_LOG
+   if [ $? != 0 ]; then
+      echo "***ERROR: Can't install EPEL rpm $epel_rpm"
+      exit -1
+   fi
 fi
 
 # to handle the case where the EPEL rpm was already
@@ -441,10 +447,10 @@ fi
 
 echo $TRAF_WORKDIR
 # Put build tar files in user's $HOME
-sudo cp $TRAF_WORKDIR/trafodion_build.tgz $HOME_DIR/$TRAF_USER &> /dev/null
-sudo cp $TRAF_WORKDIR/trafodion_server*.tgz $HOME_DIR/$TRAF_USER/trafodion_build.tgz &> /dev/null
-sudo cp $TRAF_WORKDIR/trafodion_debug*.tgz $HOME_DIR/$TRAF_USER/trafodion_build.tgz &> /dev/null
+echo $HOME_DIR/$TRAF_USER
+sudo cp $TRAF_WORKDIR/trafodion_server*.tgz $TRAF_WORKDIR/trafodion_build.tgz &> /dev/null
 sudo cp $TRAF_WORKDIR/trafodion_debug*.tgz $TRAF_WORKDIR/trafodion_build.tgz &> /dev/null
+sudo cp $TRAF_WORKDIR/trafodion_build.tgz $HOME_DIR/$TRAF_USER &> /dev/null
 sudo cp $TRAF_WORKDIR/dcs_build.tgz $HOME_DIR/$TRAF_USER &> /dev/null
 sudo cp $TRAF_WORKDIR/dcs-*.tgz $HOME_DIR/$TRAF_USER/dcs_build.tgz &> /dev/null
 sudo cp $TRAF_WORKDIR/installer/dcs_installer $HOME_DIR/$TRAF_USER
