Changes to support bulkload and DTM enabling Tlog
bulkload support

1) added code to copy the new trafodion-hbase-extensions jar file
2) added code to create two new folders under hdfs and set their permissions
3) added bulkload settings to hbase regionserver settings

DTM Tlog support

This is a coordinated change needed to support trafodion/core
change I9357aa30c201c8ec357cac7fad69101cd1bb3ff6.  Added two new
hbase regionserver settings for hlog and tlog.

Fixed chmod error discovered during review.

Change-Id: I3747c5a4fac6d57d111e4268b9642b806c068974

diff --git a/installer/traf_ambari_mods b/installer/traf_ambari_mods
--- a/installer/traf_ambari_mods
+++ b/installer/traf_ambari_mods
@@ -35,6 +35,11 @@ TRAF_BUILD=$1
 AMBARI_ADMIN=$2
 AMBARI_PASSWORD=$3
 AMBARI_URL=$4
+TRAF_VERSION=$5
+HDFS_USER=$6
+HBASE_USER=$7
+HBASE_GROUP=$8
+TRAF_USER=$9
 
 #=====================================
 # copy Trafodion hbase trx jar to /usr/lib/hbase/lib
@@ -45,13 +50,20 @@ cd $TRAF_WORKDIR
 java_version=$(ps -C java --noheader -o pid,user,cmd | grep --max-count=1 jdk | awk '{print $3}' | sed -e "s@^.*jdk\([0-9]*.[0-9]*\).*@\1@")
 echo "***INFO: Detected JAVA version $java_version"
 if [ "$java_version" == "1.6" ]; then
-	hbase_trx_jar="hbase-trx-0.8.3-java6.jar"
+	hbase_trx_jar="hbase-trx-${TRAF_VERSION}-java6.jar"
+	bulkload_jar="trafodion-hbase-extensions-${TRAF_VERSION}-java6.jar"
 else
-	hbase_trx_jar="hbase-trx-0.8.3.jar"
+	hbase_trx_jar="hbase-trx-${TRAF_VERSION}.jar"
+	bulkload_jar="trafodion-hbase-extensions-${TRAF_VERSION}.jar"
 fi
 tar -xzf $TRAF_BUILD export/lib/$hbase_trx_jar
 if [ $? != 0 ]; then
     echo "***ERROR: unable to find export/lib/$hbase_trx_jar in $TRAF_BUILD"
+    exit -1
+fi
+tar -xzf $TRAF_BUILD export/lib/$bulkload_jar
+if [ $? != 0 ]; then
+    echo "***ERROR: unable to find export/lib/$bulkload_jar in $TRAF_BUILD"
     exit -1
 fi
 
@@ -60,13 +72,50 @@ echo "***INFO: copying $hbase_trx_jar to all nodes"
 if [ $node_count -ne 1 ]; then
     pdsh $MY_NODES mkdir -p $TRAF_WORKDIR 2>/dev/null
     pdcp $MY_NODES export/lib/$hbase_trx_jar $TRAF_WORKDIR
-    pdsh $MY_NODES sudo cp $TRAF_WORKDIR/$hbase_trx_jar /usr/lib/hbase/lib
+    pdsh $MY_NODES sudo cp $TRAF_WORKDIR/$hbase_trx_jar /usr/lib/hbase/lib/
     pdsh $MY_NODES sudo chmod 644 /usr/lib/hbase/lib/$hbase_trx_jar
 else
     cp export/lib/$hbase_trx_jar $TRAF_WORKDIR
     chmod 755 $TRAF_WORKDIR/$hbase_trx_jar
-    sudo cp $TRAF_WORKDIR/$hbase_trx_jar /usr/lib/hbase/lib
+    sudo cp $TRAF_WORKDIR/$hbase_trx_jar /usr/lib/hbase/lib/
 fi
+
+echo "***INFO: copying $bulkload_jar to all nodes"
+if [ $node_count -ne 1 ]; then
+    pdsh $MY_NODES mkdir -p $TRAF_WORKDIR 2>/dev/null
+    pdcp $MY_NODES export/lib/$bulkload_jar $TRAF_WORKDIR
+    pdsh $MY_NODES sudo cp $TRAF_WORKDIR/$bulkload_jar /usr/lib/hbase/lib/
+    pdsh $MY_NODES sudo chmod 644 /usr/lib/hbase/lib/$bulkload_jar
+else
+    cp export/lib/$bulkload_jar $TRAF_WORKDIR
+    chmod 755 $TRAF_WORKDIR/$bulkload_jar
+    sudo cp $TRAF_WORKDIR/$bulkload_jar /usr/lib/hbase/lib/
+fi
+
+# create new directories for bulkload if not already there
+rm traf_temp_output 2>/dev/null
+sudo su $HDFS_USER --command "hadoop fs -mkdir /hbase-staging" 2> traf_temp_output
+if [ $? != 0 ]; then
+   # ok if directory already exists
+   dir_exists=$(grep "File exists" traf_temp_output | wc -l)
+   if [ $dir_exists -eq 0 ]; then
+      echo "***ERROR: 'hadoop fs -mkdir /hbase-staging' command failed"
+      echo "***ERROR: $(cat traf_temp_output)"
+      exit -1
+   fi
+fi
+sudo su $HDFS_USER --command "hadoop fs -chown -R $HBASE_USER:$HBASE_GROUP /hbase-staging"
+sudo su $HDFS_USER --command "hadoop fs -mkdir /bulkload"
+if [ $? != 0 ]; then
+   # ok if directory already exists
+   dir_exists=$(grep "File exists" traf_temp_output | wc -l)
+   if [ $dir_exists -eq 0 ]; then
+      echo "***ERROR: 'hadoop fs -mkdir /bulkload' command failed"
+      echo "***ERROR: $(cat traf_temp_output)"
+      exit -1
+   fi
+fi
+sudo su $HDFS_USER --command "hadoop fs -chown -R $TRAF_USER:trafodion /bulkload"
 
 #=====================================
 # change the hbase configuration using Ambari's script
@@ -76,7 +125,7 @@ if [ $? != 0 ]; then
     echo "***INFO: unable to modify hbase.master.distributed.log.splitting through Ambari's configs.sh script."
     exit -1
 fi
-$AMBARI_DIR/configs.sh set $(hostname --long) $CLUSTER_NAME hbase-site hbase.coprocessor.region.classes org.apache.hadoop.hbase.regionserver.transactional.TransactionalAggregateImpl
+$AMBARI_DIR/configs.sh set $(hostname --long) $CLUSTER_NAME hbase-site hbase.coprocessor.region.classes "org.apache.hadoop.hbase.regionserver.transactional.TransactionalAggregateImpl,org.trafodion.sql.extensions.TrafBulkLoadEndpoint"
 if [ $? != 0 ]; then
     echo "***INFO: unable to modify hbase.coprocessor.region.classes through Ambari's configs.sh script."
     exit -1
@@ -109,6 +158,21 @@ fi
 $AMBARI_DIR/configs.sh set $(hostname --long) $CLUSTER_NAME hbase-site hbase.snapshot.enabled true
 if [ $? != 0 ]; then
     echo "***INFO: unable to modify hbase.snapshot.enabled through Ambari's configs.sh script."
+    exit -1
+fi
+$AMBARI_DIR/configs.sh set $(hostname --long) $CLUSTER_NAME hbase-site hbase.bulkload.staging.dir /hbase-staging
+if [ $? != 0 ]; then
+    echo "***INFO: unable to modify hbase.bulkload.staging.dir through Ambari's configs.sh script."
+    exit -1
+fi
+$AMBARI_DIR/configs.sh set $(hostname --long) $CLUSTER_NAME hbase-site hbase.regionserver.region.transactional.tlog true
+if [ $? != 0 ]; then
+    echo "***INFO: unable to modify hbase.regionserver.region.transactional.tlog through Ambari's configs.sh script."
+    exit -1
+fi
+$AMBARI_DIR/configs.sh set $(hostname --long) $CLUSTER_NAME hbase-site hbase.regionserver.region.transactional.hlog false
+if [ $? != 0 ]; then
+    echo "***INFO: unable to modify hbase.regionserver.region.transactional.hlog through Ambari's configs.sh script."
     exit -1
 fi
 echo
diff --git a/installer/traf_cloudera_mods b/installer/traf_cloudera_mods
--- a/installer/traf_cloudera_mods
+++ b/installer/traf_cloudera_mods
@@ -35,23 +35,35 @@ TRAF_BUILD=$1
 CLOUDERA_ADMIN=$2
 CLOUDERA_PASSWORD=$3
 CLOUDERA_MANAGER_URL=$4
+TRAF_VERSION=$5
+HDFS_USER=$6
+HBASE_USER=$7
+HBASE_GROUP=$8
+TRAF_USER=$9
 
 #=====================================
 # copy Trafodion trx jar to Cloudera's plugins directory on all nodes
 
 cd $TRAF_WORKDIR
 
-# determine java version and choose corresponding jar file
+# determine java version and choose corresponding jar files
 java_version=$(ps -C java --noheader -o pid,user,cmd | grep --max-count=1 jdk | awk '{print $3}' | sed -e "s@^.*jdk\([0-9]*.[0-9]*\).*@\1@")
 echo "***INFO: Detected JAVA version $java_version"
 if [ "$java_version" == "1.6" ]; then
-	hbase_trx_jar=hbase-trx-0.8.3-java6.jar
+	hbase_trx_jar="hbase-trx-${TRAF_VERSION}-java6.jar"
+	bulkload_jar="trafodion-hbase-extensions-${TRAF_VERSION}-java6.jar"
 else
-	hbase_trx_jar=hbase-trx-0.8.3.jar
+	hbase_trx_jar="hbase-trx-${TRAF_VERSION}.jar"
+	bulkload_jar="trafodion-hbase-extensions-${TRAF_VERSION}.jar"
 fi
 tar -xzf $TRAF_BUILD export/lib/$hbase_trx_jar
 if [ $? != 0 ]; then
     echo "***ERROR: unable to find export/lib/$hbase_trx_jar in $TRAF_BUILD"
+    exit -1
+fi
+tar -xzf $TRAF_BUILD export/lib/$bulkload_jar
+if [ $? != 0 ]; then
+    echo "***ERROR: unable to find export/lib/$bulkload_jar in $TRAF_BUILD"
     exit -1
 fi
 
@@ -67,6 +79,43 @@ else
     chmod 755 $TRAF_WORKDIR/$hbase_trx_jar
     sudo cp $TRAF_WORKDIR/$hbase_trx_jar /usr/share/cmf/lib/plugins
 fi
+
+echo "***INFO: copying $bulkload_jar to all nodes"
+if [ $node_count -ne 1 ]; then
+    pdsh $MY_NODES mkdir -p $TRAF_WORKDIR 2>/dev/null
+    pdcp $MY_NODES export/lib/$bulkload_jar $TRAF_WORKDIR
+    pdsh $MY_NODES sudo cp $TRAF_WORKDIR/$bulkload_jar /usr/share/cmf/lib/plugins
+    pdsh $MY_NODES sudo chmod 644 /usr/share/cmf/lib/plugins/$bulkload_jar
+else
+    cp export/lib/$bulkload_jar $TRAF_WORKDIR
+    chmod 755 $TRAF_WORKDIR/$bulkload_jar
+    sudo cp $TRAF_WORKDIR/$bulkload_jar /usr/share/cmf/lib/plugins
+fi
+
+# create new directories for bulkload if not already there
+rm traf_temp_output 2>/dev/null
+sudo su $HDFS_USER --command "hadoop fs -mkdir /hbase-staging" 2> traf_temp_output
+if [ $? != 0 ]; then
+   # ok if directory already exists
+   dir_exists=$(grep "File exists" traf_temp_output | wc -l)
+   if [ $dir_exists -eq 0 ]; then
+      echo "***ERROR: 'hadoop fs -mkdir /hbase-staging' command failed"
+      echo "***ERROR: $(cat traf_temp_output)"
+      exit -1
+   fi
+fi
+sudo su $HDFS_USER --command "hadoop fs -chown -R $HBASE_USER:$HBASE_GROUP /hbase-staging"
+sudo su $HDFS_USER --command "hadoop fs -mkdir /bulkload" 2> traf_temp_output
+if [ $? != 0 ]; then
+   # ok if directory already exists
+   dir_exists=$(grep "File exists" traf_temp_output | wc -l)
+   if [ $dir_exists -eq 0 ]; then
+      echo "***ERROR: 'hadoop fs -mkdir /bulkload' command failed"
+      echo "***ERROR: $(cat traf_temp_output)"
+      exit -1
+   fi
+fi
+sudo su $HDFS_USER --command "hadoop fs -chown -R $TRAF_USER:trafodion /bulkload"
 
 #=====================================
 # Modify hadoop settings as needed by Trafodion
@@ -119,13 +168,13 @@ curl -X PUT -H 'Content-Type:application/json' -u $CLOUDERA_ADMIN:$CLOUDERA_PASS
 	"roleType" : "REGIONSERVER", 
 	"items" : [ { 
 		"name" : "hbase_coprocessor_region_classes", 
-                "value" : "org.apache.hadoop.hbase.regionserver.transactional.TransactionalAggregateImpl"
+                "value" : "org.apache.hadoop.hbase.regionserver.transactional.TransactionalAggregateImpl,org.trafodion.sql.extensions.TrafBulkLoadEndpoint"
 		}, {
 		"name" : "hbase_regionserver_class", 
                 "value" : "org.apache.hadoop.hbase.ipc.TransactionalRegionInterface"
 		}, {
 		"name" : "hbase_regionserver_config_safety_valve", 
-		"value" : "<property>\r\n   <name>hbase.regionserver.impl</name>\r\n   <value>org.apache.hadoop.hbase.regionserver.transactional.TransactionalRegionServer</value>\r\n</property>\r\n<property>\r\n  <name>hbase.hregion.impl</name>\r\n   <value>org.apache.hadoop.hbase.regionserver.transactional.TransactionalRegion</value>\r\n</property>\r\n<property>\r\n   <name>hbase.hlog.splitter.impl</name>\r\n   <value>org.apache.hadoop.hbase.regionserver.transactional.THLogSplitter</value>\r\n</property>\r\n<property>\r\n   <name>hbase.regionserver.region.split.policy</name>\r\n   <value>org.apache.hadoop.hbase.regionserver.ConstantSizeRegionSplitPolicy</value>\r\n</property>\r\n  <property>\r\n   <name>hbase.snapshot.enabled</name>\r\n   <value>true</value>\r\n</property>\r\n "
+		"value" : "<property>\r\n   <name>hbase.regionserver.impl</name>\r\n   <value>org.apache.hadoop.hbase.regionserver.transactional.TransactionalRegionServer</value>\r\n</property>\r\n<property>\r\n  <name>hbase.hregion.impl</name>\r\n   <value>org.apache.hadoop.hbase.regionserver.transactional.TransactionalRegion</value>\r\n</property>\r\n<property>\r\n   <name>hbase.hlog.splitter.impl</name>\r\n   <value>org.apache.hadoop.hbase.regionserver.transactional.THLogSplitter</value>\r\n</property>\r\n<property>\r\n   <name>hbase.regionserver.region.split.policy</name>\r\n   <value>org.apache.hadoop.hbase.regionserver.ConstantSizeRegionSplitPolicy</value>\r\n</property>\r\n  <property>\r\n   <name>hbase.snapshot.enabled</name>\r\n   <value>true</value>\r\n</property>\r\n <property>\r\n   <name>hbase.bulkload.staging.dir</name>\r\n   <value>/hbase-staging</value>\r\n</property>\r\n <property>\r\n   <name>hbase.regionserver.region.transactional.hlog</name>\r\n   <value>false</value>\r\n</property>\r\n <property>\r\n   <name>hbase.regionserver.region.transactional.tlog</name>\r\n   <value>true</value>\r\n</property>\r\n"
 		} ] 
 	} ] 
 }' \
@@ -141,9 +190,15 @@ fi
 curl_error=$(grep TITLE $TRAF_WORKDIR/traf_hbase_config_temp | grep Error | wc -l)
 if [ $curl_error -ne 0 ]; then
     echo "***INFO: unable to modify hbase configuration through Cloudera's REST API."
+    cat traf_hbase_config_temp
     exit -1
 fi
-
+curl_error=$(grep message $TRAF_WORKDIR/traf_hbase_config_temp | wc -l)
+if [ $curl_error -ne 0 ]; then
+    echo "***INFO: unable to modify hbase configuration through Cloudera's REST API."
+    cat traf_hbase_config_temp
+    exit -1
+fi
 rm $TRAF_WORKDIR/traf_hbase_config_temp 2> /dev/null
 
 #=====================================
