1440837 bug fix and ssh error catching
Testing sudo access on all nodes.

Added error checking to make sure all nodes entered are valid.

Edit 1: Small change to error checking

Change-Id: Ife2c6ec9769be94b9f26a9c94fef74c9c1b43d56

diff --git a/installer/traf_config_setup b/installer/traf_config_setup
--- a/installer/traf_config_setup
+++ b/installer/traf_config_setup
@@ -209,7 +209,13 @@ else
    NODE_LIST=""
    for node in $NODES
    do
-      newNode=$(ssh -n $node hostname)
+      newNode=$(ssh -n $node hostname 2>&1 >/dev/null)
+      
+      if [[ $? -ne "0" ]]; then
+         echo "***ERROR: $newNode"
+         echo "***ERROR: Please check node names for typos"
+         exit -1
+      fi
 
       nodeName=$(echo $newNode | sed 's/[^a-zA-Z0-9\ \.\-]//g')
 
@@ -222,6 +228,14 @@ else
       if [[ "$newNode" =~ ^([0-9]{1,3})[.]([0-9]{1,3})[.]([0-9]{1,3})[.]([0-9]{1,3})$ ]]; then
          echo "***ERROR: Nodes are not named properly."
          echo "***ERROR: IP addresses are not supported. Please use node names."
+         exit -1
+      fi
+    
+      #Testing sudo access on all nodes
+      ssh -n $node sudo echo "***INFO: Testing sudo access on node $node"
+      if [ $? -ne "0" ]; then
+         echo "***ERROR: Node $node does not have sudo access."
+         echo "***ERROR: Must have sudo access on all nodes."
          exit -1
       fi
       
