Fixed pdsh issue
pdsh was being called before it might have been installed. Now
installing pdsh during traf_config_setup since it will be needed.

Change-Id: Ied68568826c0edffb6251313722b4d98586a03ab

diff --git a/installer/traf_config_setup b/installer/traf_config_setup
--- a/installer/traf_config_setup
+++ b/installer/traf_config_setup
@@ -712,6 +712,46 @@ echo "export DCS_SERVERS_PARM=\"$DCS_SERVERS_PARM\"" >> $LOCAL_TRAF_CONFIG
 echo "export CONFIG_COMPLETE=\"true\"" >> $LOCAL_TRAF_CONFIG
 #=============================================
 
+#Need to add test for internet access
+internetAccess=true
+
+YUM_LOG=/var/log/trafodion/trafodion_yum_$timestamp.log
+
+# first install pdsh on each node so we can use it to install
+# everything else.  don't need pdsh if only a single node
+if [ $node_count -ne 1 ]; then
+    for node in $NODE_LIST
+    do
+        echo "***INFO: ... pdsh on node $node"
+
+        # if not already installed on this node, then install it
+        ssh $node rpm -qa | grep pdsh &> /dev/null
+        if [ $? -ne 0 ]; then
+            ssh $node sudo mkdir -p $TRAF_WORKDIR
+            ssh $node sudo mkdir -p /var/log/trafodion
+            if [[ $internetAccess == "true" ]]; then
+               ssh $node sudo yum --assumeyes install pdsh &>> $YUM_LOG
+               if [ $? != 0 ]; then
+                  echo "***ERROR: Can't install pdsh on node $node"
+                  exit -1
+               fi
+            else
+               echo "***ERROR: Can't install pdsh on node $node"
+               echo "***ERROR: Must have pdsh installed on each node."
+               echo "***ERROR: No internet access to do automatic install."
+               exit -1
+            fi
+        fi
+    done
+    # create working directory on all nodes
+    $TRAF_PDSH mkdir -p $TRAF_WORKDIR &> /dev/null
+    $TRAF_PDSH mkdir -p /var/log/trafodion &> /dev/null
+
+fi
+
+#=============================================
+#Create directories and cp files
+
 $TRAF_PDSH sudo mkdir -p $TRAF_CONFIG_DIR
 $TRAF_PDSH sudo chmod 777 $TRAF_CONFIG_DIR
 sudo cp $LOCAL_TRAF_CONFIG $TRAF_CONFIG
