Merge the private shared single script repo into master.
This is a checkin of the single script project which basically
wraps all the various scripts into one single script that the user
runs.  The script now has the logic to determine which Hadoop distro
is installed as well as to determine if it is a full install or only
an upgrade and many other changes.

This was developed and tested in a private shared repo so
a review of the code has already been done.  QA has approved this
to be checked in.

edit1: fixed shift problem in parsing parameters
edit2: Fixed problems with user config file
       Added more error checking for config file
edit3: Fixed config directory creation
edit4: Fixed copyright and OpenStack VM package installation
edit5: Changed Java version detection
       No longer do yum removes if package is there already
edit6: Refixed OpenStack VM package installation that got
          overlaid in a merge
       Added chown command to handle case where SQ_ROOT was not
          a sub-directory of the Trafodion userid's home dir

Change-Id: I37a331c89c311feee430541b69f5f7dfe2177e60

diff --git a/installer/traf_hortonworks_mods98 b/installer/traf_hortonworks_mods98
--- a/installer/traf_hortonworks_mods98
+++ b/installer/traf_hortonworks_mods98
@@ -2,7 +2,7 @@
 
 # @@@ START COPYRIGHT @@@
 #
-# (C) Copyright 2013-2014 Hewlett-Packard Development Company, L.P.
+# (C) Copyright 2013-2015 Hewlett-Packard Development Company, L.P.
 #
 #  Licensed under the Apache License, Version 2.0 (the "License");
 #  you may not use this file except in compliance with the License.
@@ -25,31 +25,17 @@
 #
 # NOTE: Only for Ambari installations
 
-###Default Values###
-typeset TRAF_WORKDIR="$( cd "$( dirname "$0" )" && pwd )/.."
-NODE_LIST=$(cat $TRAF_WORKDIR/node_list)
-MY_NODES=$(cat $TRAF_WORKDIR/my_nodes)
-node_count=$(echo $NODE_LIST | wc -w)
-
-TRAF_BUILD=$1
-AMBARI_ADMIN=$2
-AMBARI_PASSWORD=$3
-AMBARI_URL=$4
-TRAF_VERSION=$5
-HDFS_USER=$6
-HBASE_USER=$7
-HBASE_GROUP=$8
-TRAF_USER=$9
-JAVA_VERSION=${10}
+TRAF_CONFIG=/etc/trafodion/trafodion_config
+source $TRAF_CONFIG
 
 #=====================================
 # copy Trafodion hbase trx jar to /usr/lib/hbase/lib
 
-cd $TRAF_WORKDIR
+cd $UNTAR_DIR
 
-PORT=`echo $AMBARI_URL | sed 's/.*://'`
+PORT=`echo $URL | sed 's/.*://'`
 echo $PORT 
-AMBARI_HOST=$(echo $AMBARI_URL | sed 's@:.*@@')
+AMBARI_HOST=$(echo $URL | sed 's@:.*@@')
 echo $AMBARI_HOST
 
 # determine java version and choose corresponding jar files
@@ -63,48 +49,59 @@ else
     echo "***ERROR: unable to determine Hadoop's java version"
     exit -1
 fi
-if [ ! -f export/lib/$hbase_trx_jar ]; then
-    echo "***ERROR: unable to find export/lib/$hbase_trx_jar in $TRAF_BUILD"
+
+# The permissions the Trafodion build process creates on the hbase-trx jar
+# files does not work well with the installation process so we change them
+sudo chmod -R 777 $UNTAR_DIR/export/lib
+
+if [ ! -f $UNTAR_DIR/export/lib/$hbase_trx_jar ]; then
+    echo "***ERROR: unable to find $UNTAR_DIR/export/lib/$hbase_trx_jar"
     exit -1
 fi
 
 # if more than one node then copy to all nodes
 echo "***INFO: copying $hbase_trx_jar to all nodes"
 if [ $node_count -ne 1 ]; then
-    pdsh $MY_NODES mkdir -p $TRAF_WORKDIR 2>/dev/null
     pdsh $MY_NODES sudo rm -rf /usr/lib/hbase/lib/hbase-trx* 2>/dev/null
+    pdsh $MY_NODES sudo rm -rf /usr/share/cmf/lib/plugins/hbase-trx* 2>/dev/null
     pdsh $MY_NODES sudo rm -rf /usr/lib/hbase/lib/trafodion* 2>/dev/null
-    pdcp $MY_NODES export/lib/$hbase_trx_jar $TRAF_WORKDIR
-    pdsh $MY_NODES sudo cp $TRAF_WORKDIR/$hbase_trx_jar /usr/lib/hbase/lib/
+    pdsh $MY_NODES sudo rm -rf /usr/share/cmf/lib/plugins/trafodion* 2>/dev/null
+    pdsh $MY_NODES mkdir -p $PWD 2>/dev/null
+    cp $UNTAR_DIR/export/lib/$hbase_trx_jar $LOCAL_WORKDIR
+    pdcp $MY_NODES $LOCAL_WORKDIR/$hbase_trx_jar $LOCAL_WORKDIR
+    pdsh $MY_NODES sudo cp $LOCAL_WORKDIR/$hbase_trx_jar /usr/lib/hbase/lib
     pdsh $MY_NODES sudo chmod 644 /usr/lib/hbase/lib/$hbase_trx_jar
+    pdsh $MY_NODES rm $LOCAL_WORKDIR/$hbase_trx_jar 2>/dev/null
 else
     sudo rm -rf /usr/lib/hbase/lib/hbase-trx* 2>/dev/null
+    sudo rm -rf /usr/share/cmf/lib/plugins/hbase-trx* 2>/dev/null
     sudo rm -rf /usr/lib/hbase/lib/trafodion* 2>/dev/null
-    cp export/lib/$hbase_trx_jar $TRAF_WORKDIR
-    chmod 644 $TRAF_WORKDIR/$hbase_trx_jar
-    sudo cp $TRAF_WORKDIR/$hbase_trx_jar /usr/lib/hbase/lib/
+    sudo rm -rf /usr/share/cmf/lib/plugins/trafodion* 2>/dev/null
+    sudo cp $UNTAR_DIR/export/lib/$hbase_trx_jar /usr/lib/hbase/lib
+    sudo chmod 644 /usr/lib/hbase/lib/$hbase_trx_jar
 fi
 
 # create new directories for bulkload if not already there
-rm traf_temp_output 2>/dev/null
-sudo su $HDFS_USER --command "hadoop fs -mkdir /hbase-staging" 2> traf_temp_output
+rm $LOCAL_WORKDIR/traf_temp_output 2>/dev/null
+
+sudo su $HDFS_USER --command "hadoop fs -mkdir /hbase-staging" 2> $LOCAL_WORKDIR/traf_temp_output
 if [ $? != 0 ]; then
    # ok if directory already exists
-   dir_exists=$(grep "File exists" traf_temp_output | wc -l)
+   dir_exists=$(grep "File exists" $LOCAL_WORKDIR/traf_temp_output | wc -l)
    if [ $dir_exists -eq 0 ]; then
       echo "***ERROR: 'hadoop fs -mkdir /hbase-staging' command failed"
-      echo "***ERROR: $(cat traf_temp_output)"
+      echo "***ERROR: $(cat $LOCAL_WORKDIR/traf_temp_output)"
       exit -1
    fi
 fi
 sudo su $HDFS_USER --command "hadoop fs -chown -R $HBASE_USER:$HBASE_GROUP /hbase-staging"
-sudo su $HDFS_USER --command "hadoop fs -mkdir /bulkload"
+sudo su $HDFS_USER --command "hadoop fs -mkdir /bulkload" 2> $LOCAL_WORKDIR/traf_temp_output
 if [ $? != 0 ]; then
    # ok if directory already exists
-   dir_exists=$(grep "File exists" traf_temp_output | wc -l)
+   dir_exists=$(grep "File exists" $LOCAL_WORKDIR/traf_temp_output | wc -l)
    if [ $dir_exists -eq 0 ]; then
       echo "***ERROR: 'hadoop fs -mkdir /bulkload' command failed"
-      echo "***ERROR: $(cat traf_temp_output)"
+      echo "***ERROR: $(cat $LOCAL_WORKDIR/traf_temp_output)"
       exit -1
    fi
 fi
@@ -112,74 +109,149 @@ sudo su $HDFS_USER --command "hadoop fs -chown -R $TRAF_USER:trafodion /bulkload
 
 #=====================================
 # change the hbase configuration using Ambari's script
+
 AMBARI_DIR=/var/lib/ambari-server/resources/scripts
+cd $LOCAL_WORKDIR
+
 $AMBARI_DIR/configs.sh -port $PORT set $AMBARI_HOST $CLUSTER_NAME hbase-site hbase.master.distributed.log.splitting false
 if [ $? != 0 ]; then
-    echo "***INFO: unable to modify hbase.master.distributed.log.splitting through Ambari's configs.sh script."
+    echo "***ERROR: unable to modify hbase.master.distributed.log.splitting through Ambari's configs.sh script."
+    echo "***ERROR: Check if Ambari URL is correct, may need to enter external IP address."
+    echo "***ERROR: Check that HBase is running without error."
     exit -1
 fi
 sleep 2
 $AMBARI_DIR/configs.sh -port $PORT set $AMBARI_HOST $CLUSTER_NAME hbase-site hbase.coprocessor.region.classes "org.apache.hadoop.hbase.coprocessor.transactional.TrxRegionObserver,org.apache.hadoop.hbase.coprocessor.transactional.TrxRegionEndpoint,org.apache.hadoop.hbase.coprocessor.AggregateImplementation"
 if [ $? != 0 ]; then
-    echo "***INFO: unable to modify hbase.coprocessor.region.classes through Ambari's configs.sh script."
+    echo "***ERROR: unable to modify hbase.coprocessor.region.classes through Ambari's configs.sh script."
     exit -1
 fi
 sleep 2
 $AMBARI_DIR/configs.sh -port $PORT set $AMBARI_HOST $CLUSTER_NAME hbase-site hbase.hregion.impl org.apache.hadoop.hbase.regionserver.transactional.TransactionalRegion
 if [ $? != 0 ]; then
-    echo "***INFO: unable to modify hbase.hregion.impl through Ambari's configs.sh script."
+    echo "***ERROR: unable to modify hbase.hregion.impl through Ambari's configs.sh script."
     exit -1
 fi
 sleep 2
 $AMBARI_DIR/configs.sh -port $PORT set $AMBARI_HOST $CLUSTER_NAME hbase-site hbase.regionserver.region.split.policy org.apache.hadoop.hbase.regionserver.ConstantSizeRegionSplitPolicy
 if [ $? != 0 ]; then
-    echo "***INFO: unable to modify hbase.regionserver.region.split.policy through Ambari's configs.sh script."
+    echo "***ERROR: unable to modify hbase.regionserver.region.split.policy through Ambari's configs.sh script."
     exit -1
 fi
 sleep 2 
 $AMBARI_DIR/configs.sh -port $PORT set $AMBARI_HOST $CLUSTER_NAME hbase-site hbase.snapshot.enabled true
 if [ $? != 0 ]; then
-    echo "***INFO: unable to modify hbase.snapshot.enabled through Ambari's configs.sh script."
+    echo "***ERROR: unable to modify hbase.snapshot.enabled through Ambari's configs.sh script."
     exit -1
 fi
 sleep 2
 $AMBARI_DIR/configs.sh -port $PORT set $AMBARI_HOST $CLUSTER_NAME hbase-site hbase.bulkload.staging.dir /hbase-staging
 if [ $? != 0 ]; then
-    echo "***INFO: unable to modify hbase.bulkload.staging.dir through Ambari's configs.sh script."
+    echo "***ERROR: unable to modify hbase.bulkload.staging.dir through Ambari's configs.sh script."
     exit -1
 fi
 sleep 2
 $AMBARI_DIR/configs.sh -port $PORT set $AMBARI_HOST $CLUSTER_NAME hbase-site hbase.regionserver.region.transactional.tlog true
 if [ $? != 0 ]; then
-    echo "***INFO: unable to modify hbase.regionserver.region.transactional.tlog through Ambari's configs.sh script."
+    echo "***ERROR: unable to modify hbase.regionserver.region.transactional.tlog through Ambari's configs.sh script."
     exit -1
 fi
 sleep 2
 $AMBARI_DIR/configs.sh -port $PORT set $(hostname --long) $CLUSTER_NAME hbase-site hbase.snapshot.master.timeoutMillis 600000
 if [ $? != 0 ]; then
-    echo "***INFO: unable to modify hbase.snapshot.master.timeoutMillis through Ambari's configs.sh script."
+    echo "***ERROR: unable to modify hbase.snapshot.master.timeoutMillis through Ambari's configs.sh script."
     exit -1
 fi
 sleep 2
 $AMBARI_DIR/configs.sh -port $PORT set $(hostname --long) $CLUSTER_NAME hbase-site hbase.snapshot.region.timeout 600000
 if [ $? != 0 ]; then
-    echo "***INFO: unable to modify hbase.snapshot.region.timeout through Ambari's configs.sh script."
-    exit -1
-fi
-sleep 2
-$AMBARI_DIR/configs.sh -port $PORT set $(hostname --long) $CLUSTER_NAME hbase-site ipc.server.tcpnodelay true
-if [ $? != 0 ]; then
-    echo "***INFO: unable to modify ipc.server.tcpnodelay through Ambari's configs.sh script."
-    exit -1
-fi
-sleep 2
-$AMBARI_DIR/configs.sh -port $PORT set $(hostname --long) $CLUSTER_NAME hbase-site ipc.client.tcpnodelay true
-if [ $? != 0 ]; then
-    echo "***INFO: unable to modify ipc.client.tcpnodelay through Ambari's configs.sh script."
+    echo "***ERROR: unable to modify hbase.snapshot.region.timeout through Ambari's configs.sh script."
     exit -1
 fi
 sleep 2
 echo
-echo "***WARNING: Please manually restart HBase through the Ambari web GUI"
-echo
+
+#=====================================
+# restart HBase to pick up all the changes just made
+
+poll_time=30
+echo "***INFO: Restarting HBase to pick up config changes for Trafodion"
+echo "***INFO: Stopping HBase..."
+curl -u $ADMIN:$PASSWORD \
+    -H "X-Requested-By: Trafodion" \
+    -X PUT -d '{"ServiceInfo": { "state" : "INSTALLED" }}' \
+    http://$URL/api/v1/clusters/$CLUSTER_NAME/services/HBASE > $TRAF_WORKDIR/traf_hbase_restart_temp
+
+if [ $? != 0 ]; then 
+   echo "***ERROR: Unable to restart HBase"
+   echo "***ERROR: Please manually restart HBase through the Ambari web GUI"
+fi 
+
+# in most cases curl does not return an error
+# so curl's actual output needs to be checked, too
+curl_error=$(grep TITLE $TRAF_WORKDIR/traf_hbase_restart_temp | grep Error | wc -l)
+
+if [ $curl_error -ne 0 ]; then
+    echo "***ERROR: Unable to restart HBase"
+    echo "***ERROR: Please manually restart HBase through the Ambari web GUI"
+fi
+
+echo "***INFO: ...polling every $poll_time seconds until restart is completed."
+command_id=$(cat $TRAF_WORKDIR/traf_hbase_restart_temp | grep id | awk '{print $3}' | sed -e 's@,@@' )
+echo "***DEBUG: Ambari command_id=$command_id"
+
+# poll until stop is completed as a stop can take a while
+completed=0
+while [ $completed -eq 0 ]; do
+    sleep $poll_time
+    curl -u $ADMIN:$PASSWORD \
+        http://$URL/api/v1/clusters/$CLUSTER_NAME/requests/$command_id \
+        > $LOCAL_WORKDIR/hbase_restart_status_temp
+    cat $LOCAL_WORKDIR/hbase_restart_status_temp
+    echo "***INFO: ...polling every $poll_time seconds until stop is completed."
+    # if stop command is completed then completed will not equal 0
+    completed=$(cat $LOCAL_WORKDIR/hbase_restart_status_temp | grep '"request_status" : "COMPLETED"' | wc -l)
+done
+
+echo "***INFO: Starting HBase..."
+curl -u $ADMIN:$PASSWORD \
+    -H "X-Requested-By: Trafodion" \
+    -X PUT -d '{"ServiceInfo": { "state" : "STARTED" }}' \
+    http://$URL/api/v1/clusters/$CLUSTER_NAME/services/HBASE > $TRAF_WORKDIR/traf_hbase_restart_temp
+
+if [ $? != 0 ]; then
+   echo "***ERROR: Unable to restart HBase"
+   echo "***ERROR: Please manually restart HBase through the Ambari web GUI"
+fi
+
+# in most cases curl does not return an error
+# so curl's actual output needs to be checked, too
+curl_error=$(grep TITLE $TRAF_WORKDIR/traf_hbase_restart_temp | grep Error | wc -l)
+if [ $curl_error -ne 0 ]; then
+    echo "***ERROR: Unable to restart HBase"
+    echo "***ERROR: Please manually restart HBase through the Ambari web GUI"
+fi
+
+echo "***INFO: ...polling every $poll_time seconds until start is completed."
+command_id=$(cat $TRAF_WORKDIR/traf_hbase_restart_temp | grep id | awk '{print $3}' | sed -e 's@,@@' )
+echo "***DEBUG: Ambari command_id=$command_id"
+
+# poll until stop is completed as a stop can take a while
+completed=0
+while [ $completed -eq 0 ]; do
+    sleep $poll_time
+    curl -u $ADMIN:$PASSWORD \
+        http://$URL/api/v1/clusters/$CLUSTER_NAME/requests/$command_id \
+        > $LOCAL_WORKDIR/hbase_restart_status_temp
+    cat $LOCAL_WORKDIR/hbase_restart_status_temp
+    echo "***INFO: ...polling every $poll_time seconds until stop is completed."
+    # if start command is completed then completed will not equal 0
+    completed=$(cat $LOCAL_WORKDIR/hbase_restart_status_temp | grep '"request_status" : "COMPLETED"' | wc -l)
+done
+
+# clean up files generated by Ambari's config.sh script
+rm $LOCAL_WORKDIR/doSet_version*
+
+echo "***INFO: HBase restart completed successfully"
+
 exit
diff --git a/installer/traf_installer b/installer/traf_installer
--- a/installer/traf_installer
+++ b/installer/traf_installer
@@ -2,7 +2,7 @@
 
 # @@@ START COPYRIGHT @@@
 #
-# (C) Copyright 2013-2014 Hewlett-Packard Development Company, L.P.
+# (C) Copyright 2013-2015 Hewlett-Packard Development Company, L.P.
 #
 #  Licensed under the Apache License, Version 2.0 (the "License");
 #  you may not use this file except in compliance with the License.
@@ -22,159 +22,38 @@
 #==========================================
 # Install Trafodion build on a Cluster System
 #==========================================
-
-function print_usage {
-cat << EOF
-This script will install a specified Trafodion build.
-
-Usage: $(basename $0) [options]
-
-Options:
-    --help                Print this message and exit.
-    --build <file>        Full pathname to the Trafodion build tar file.
-    --dcs_build <file>    Full pathname to the DCS build tar file.
-    --install_path <dir>  Full pathname to the install directory location.
-    --nostart             This will install but not start Trafodion
-    --init_trafodion      Run init_trafodion after sqstart (ignored for --nostart)
-    --config <file>       Full pathname of sqconfig. (default $HOME/sqconfig)
-    --dcs_servers <count>     Total number of DCS servers to start.  These
-                              will be allocated in a round-robin fashion on
-                              all nodes. (default, 1 per node)
-    --userid              username if not chosen will default to admin 
-    --password            password if not chosen will default to admin
-    --url                 url:port if not chosen will default to distribution default
-
-EOF
-}
-
-#============================================
 # Default values
 
 # This is the directory where all the Trafodion install scripts and
 # tar files are initially downloaded to
-typeset TRAF_WORKDIR="$( cd "$( dirname "$0" )" && pwd )"
-
+typeset TRAF_WORKDIR="$( cd "$( dirname "$0" )" && pwd )/.."
+echo $TRAF_WORKDIR
 # input parameter defaults
-typeset BUILD_FILE=""
-typeset SQ_ROOT="$HOME/trafodion"
 typeset NODES="$HOSTNAME"
-typeset DCS_BUILD="$HOME/dcs_build.tgz"
-typeset INIT_TRAFODION="N"
-typeset NOSTART="N"
-typeset SQCONFIG=""
 typeset DCS_SERVERS_PARM=""
-typeset USER_NAME="admin"
-typeset PASSWORD="admin"
 typeset timestamp=$(date +%F-%H-%M-%S)
 typeset INSTALL_LOG="/var/log/trafodion/trafodion_install_$timestamp.log"
+
+TRAF_CONFIG=/etc/trafodion/trafodion_config
+source $TRAF_CONFIG
 #============================================
 
-CLOUDERA=$(rpm -qa | grep cloudera | wc -l)
-AMBARI=$(rpm -qa | grep ambari | wc -l)
-
-if [[ $CLOUDERA -ne 0 ]]; then
-   typeset URL_PORT=$(hostname --long):7180
-fi
-
-if [[ $AMBARI -ne 0 ]]; then
-   typeset URL_PORT=$(hostname --long):8080   
-fi
-#============================================
-
-# Parse input parameters
-while [[ $# -gt 0 ]]; do
-    case "$1" in
-        --build)
-            if [[ -z "$2" ]]; then
-                echo "***ERROR: No value passed to param $1." | tee -a $INSTALL_LOG
-                print_usage
-                exit -1
-            fi
-            BUILD_FILE="$( readlink -f $2 )"
-            shift
-            ;;
-        --install_path)
-            if [[ -z "$2" ]]; then
-                echo "***ERROR: No value passed to param $1." | tee -a $INSTALL_LOG
-                print_usage
-                exit -1
-            fi
-            SQ_ROOT="$( readlink -f $2 )"
-            shift
-            ;;
-        --dcs_build)
-            if [[ -z "$2" ]]; then
-                echo "***ERROR: No value passed to param $1." | tee -a $INSTALL_LOG
-                print_usage
-                exit -1
-            fi
-            DCS_BUILD="$( readlink -f $2 )"
-            shift
-            ;;
-        --config)
-            if [[ -z "$2" ]]; then
-                echo "***ERROR: No value passed to param $1." | tee -a $INSTALL_LOG
-                print_usage
-                exit -1
-            fi
-            SQCONFIG="$( readlink -f $2 )"
-            shift
-            ;;
-        --dcs_servers)
-            if [[ -z "$2" ]]; then
-                echo "***ERROR: No value passed to param $1." | tee -a $INSTALL_LOG
-                print_usage
-                exit -1
-            fi
-            DCS_SERVERS_PARM="--dcs_servers $2"
-            shift
-            ;;
-        --init_trafodion)
-            INIT_TRAFODION="Y"
-            ;;
-        --nostart)
-            NOSTART="Y"
-            ;;
-        --userid)
-          shift
-          USER_NAME=$1
-          ;;
-        --password)
-          shift
-          PASSWORD=$1
-          ;;
-        --url)
-          shift
-          URL_PORT=$1
-          ;;
-        --help)
-            print_usage
-            exit -1 
-            ;;
-        *)
-            print_usage
-            exit -1 
-    esac
-    shift
-done
-
-#============================================
 #Info for log file
 
-echo "***INFO: Log file location /var/log/trafodion"
+echo "***INFO: Log file location $INSTALL_LOG"
 
-echo "***Log File: trafodion_installer script***" >> $INSTALL_LOG
+echo "***INFO: ***Log File: traf_installer script***" >> $INSTALL_LOG
 echo >> $INSTALL_LOG
-echo "Working directory: $TRAF_WORKDIR" >> $INSTALL_LOG
-echo "Build: $BUILD_FILE" >> $INSTALL_LOG
-echo "Install Path: $SQ_ROOT" >> $INSTALL_LOG
-echo "DCS Build: $DCS_BUILD" >> $INSTALL_LOG
-echo "Path to SQCONFIG: $SQCONFIG" >> $INSTALL_LOG
-echo "Number of DCS Servers: $DCS_SERVERS_PARM" >> $INSTALL_LOG
-echo "Run init_trafodion: $INIT_TRAFODION" >> $INSTALL_LOG
-echo "Start Trafodion: $NOSTART" >> $INSTALL_LOG
-echo "User Id: $USER_NAME" >> $INSTALL_LOG
-echo "URL: $URL_PORT" >> $INSTALL_LOG
+echo "***INFO: Working directory: $TRAF_WORKDIR" >> $INSTALL_LOG
+echo "***INFO: Build: $BUILD_FILE" >> $INSTALL_LOG
+echo "***INFO: Install Path: $SQ_ROOT" >> $INSTALL_LOG
+echo "***INFO: DCS Build: $DCS_BUILD" >> $INSTALL_LOG
+echo "***INFO: Path to SQCONFIG: $SQCONFIG" >> $INSTALL_LOG
+echo "***INFO: Number of DCS Servers: $DCS_SERVERS_PARM" >> $INSTALL_LOG
+echo "***INFO: Run init_trafodion: $INIT_TRAFODION" >> $INSTALL_LOG
+echo "***INFO: Start Trafodion: $START" >> $INSTALL_LOG
+echo "***INFO: User Id: $USER_NAME" >> $INSTALL_LOG
+echo "***INFO: Hadoop UI URL: $URL_PORT" >> $INSTALL_LOG
 echo >> $INSTALL_LOG
 
 #============================================
@@ -190,62 +69,28 @@ if [[ "$userId" != "trafodion" ]]; then
 fi
 
 #============================================
-timestamp=$(date +%F-%H-%M-%S)
 echo "***INFO: Starting Trafodion installer ($timestamp)" | tee -a $INSTALL_LOG
 
-if [ $CLOUDERA -ne 0 -o $AMBARI -ne 0 ]; then
-  #===========================================
-  # Check that Cloudera or Ambari username, password, and url are correct.
-  # Will not get a cluster name if these are not correct. Skip this for
-  # MapR and other clusters.
-
-  CLUSTER_NAME=$(curl -su $USER_NAME:$PASSWORD http://$URL_PORT/api/v1/clusters |grep name | sed -e 's@[,]@@'g | awk '{print $3}' | sed "s/\"//g")
-
-  if [ -z $CLUSTER_NAME ]; then
-    echo
-    echo "***ERROR: Please check userid, password, and url and try again. " | tee -a $INSTALL_LOG
-    echo
-    exit -1
-  fi
-fi
-
-node_count=$(echo $NODE_LIST | wc -w)
 #============================================
 # Check if an existing instance is up
 process_count=$(cstat -noheader 2>/dev/null | wc -l)
 if [ "$process_count" -ne 0 ]; then
-    echo "***ERROR: Trafodion processes are still running. Please stop the current" | tee -a $INSTALL_LOG
-    echo "***ERROR: instance with sqstop before installing a new Trafodion build." | tee -a $INSTALL_LOG
+    echo "***ERROR: There appears to be $process_count Trafodion processes still running." | tee -a $INSTALL_LOG
+    echo "***ERROR: You can verify this with the 'cstat' command." | tee -a $INSTALL_LOG
+    echo "***ERROR: Please stop the current instance with sqstop before" | tee -a $INSTALL_LOG
+    echo "***ERROR: installing a new Trafodion build." | tee -a $INSTALL_LOG
     exit -1
 fi
 
 #============================================
 # Create install directory
 mkdir -p $SQ_ROOT
+echo $SQ_ROOT
 cd $SQ_ROOT
 
-# Did the user specify a buildfile? if not apply defaults
-if [ "$BUILD_FILE" == "" ]; then
-
-    # Look for any Trafodion_server*.tgz file first
-    # and take the newest one, if any
-    file_list=$(ls -rt $HOME/trafodion_server*.tgz 2>/dev/null)
-    if [ "$file_list" != "" ]; then
-        for build in $file_list
-        do
-            BUILD_FILE=$build
-            break;
-        done
-
-    else
-        # Otherwise use this as the default
-        BUILD_FILE="$HOME/trafodion_build.tgz"
-    fi
-fi
-
 # untar Trafodion build into install directory
-echo "***INFO: untarring build file $BUILD_FILE to $SQ_ROOT" | tee -a $INSTALL_LOG
-tar -xzf $BUILD_FILE
+echo "***INFO: untarring build file $TRAF_BUILD to $SQ_ROOT" | tee -a $INSTALL_LOG
+tar -xzf $TRAF_BUILD 2>&1 | tee -a $INSTALL_LOG
 if [ "$?" != "0" ]; then
     echo "***ERROR: There was a problem untarring the Trafodion build file.  Check install log files for details." | tee -a $INSTALL_LOG
     exit -1;
@@ -279,7 +124,7 @@ else
 fi
 #============================================
 
-echo "***INFO: modifying .bashrc to set SQ_HOME, TOOLSDIR, MY_NODES and NODE_LIST" | tee -a $INSTALL_LOG
+echo "***INFO: modifying .bashrc to set Trafodion environment variables" | tee -a $INSTALL_LOG
 cd $HOME
 cp .bashrc bashrc_temp
 # NOTE: have to use '@' as delimiter because the usual slash '/' doesn't work
@@ -337,17 +182,6 @@ fi
 
 cd $SQ_ROOT
 
-# if Cloudera installed, modify SQ_CLASSPATH
-cloudera_installed=$(rpm -qa | grep cloudera | wc -l )
-if [ $cloudera_installed -ge 1 ]; then
-    echo "***INFO: Modifying sqenvcom.sh for Cloudera distro" | tee -a $INSTALL_LOG
-    cp $MY_SQROOT/sqenvcom.sh sqenvcom.sh_temp
-    sed -e "s@^SQ_CLASSPATH=\$@SQ_CLASSPATH=$MY_SQROOT/conf@" <sqenvcom.sh_temp >$MY_SQROOT/sqenvcom.sh
-
-    # re-source .bashrc to pick up these changes
-    source ~/.bashrc
-fi
-
 #=================================================
 
 if [ "$node_count" -ne "1" ]; then
@@ -373,25 +207,7 @@ fi
 #==========================================
 # install dcs
 
-# did the user specify a dcs build file? if not apply defaults
-if [ "$DCS_BUILD" == "" ]; then
-
-    # look for any dcs-*.tgz file first
-    # and take the newest one, if any
-    file_list=$(ls -rt $HOME/dcs-*.tgz)
-    if [ "$file_list" != "" ]; then
-        for build in $file_list
-        do
-            BUILD_FILE=$HOME/$build
-            break;
-        done
-
-    else
-        # otherwise use this as the default
-        BUILD_FILE="$HOME/dcs_build.tgz"
-    fi
-fi
-$TRAF_WORKDIR/dcs_installer --dcs_build $DCS_BUILD $DCS_SERVERS_PARM
+$TRAF_WORKDIR/installer/dcs_installer --dcs_build $DCS_BUILD --dcs_servers $DCS_SERVERS_PARM
 if [ "$?" != "0" ]; then
     echo "***ERROR: DCS install failed.  Check install log files for details." | tee -a $INSTALL_LOG
     exit -1;
@@ -409,8 +225,8 @@ if [ "$node_count" -ne "1" ]; then
    fi
 fi
 
-if [ "$NOSTART" == "Y" ]; then
-    echo "***INFO: --nostart was specified, skipping sqstart." | tee -a $INSTALL_LOG
+if [ "$START" == "N" ]; then
+    echo "***INFO: Trafodion will not be started, skipping sqstart." | tee -a $INSTALL_LOG
 else
     echo "***INFO: starting Trafodion instance" | tee -a $INSTALL_LOG
 
@@ -421,25 +237,43 @@ else
     SQSTART_RC=$?
     if [ "$SQSTART_RC" != "0" ]; then
         echo "***ERROR: sqstart failed with RC=$SQSTART_RC. Check $MY_SQROOT/sqmon.log file for details." | tee -a $INSTALL_LOG
+        echo "***ERROR: Consider running trafodion_scanner, to assist in debugging." | tee -a $INSTALL_LOG
         exit -1;
     fi
 
     # Do init_trafodion if specified
-    if [ "$INIT_TRAFODION" == "Y" ]; then
-        ssh $STARTING_NODE "cd $MY_SQROOT/sql/scripts;  echo \"initialize Trafodion;\" | sqlci"
+    if [ "$INIT_TRAFODION" == "Y" ] && [ "$UPGRADE_TRAF" == "false" ]; then
+        ssh $STARTING_NODE "cd $MY_SQROOT/sql/scripts;  echo \"initialize Trafodion;\" | sqlci" | tee -a initializeErrors.txt
+        foundError=$(grep "ERROR" initializeErrors.txt | wc -l)
+        if [ "$foundError" -ge "1" ]; then
+           ssh $STARTING_NODE "cd $MY_SQROOT/sql/scripts;  echo \"initialize Trafodion, upgrade;\" | sqlci"
+        fi
+        
+        if [ "$?" != "0" ]; then 
+           echo "***ERROR: initialize Trafodion failed.  Check install log files for details." | tee -a $INSTALL_LOG
+           exit -1;
+        fi
+    fi
+     # Do init_trafodion, upgrade if specified
+    if [ "$INIT_TRAFODION" == "Y" ] && [ "$UPGRADE_TRAF" == "true" ]; then
+        ssh $STARTING_NODE "cd $MY_SQROOT/sql/scripts;  echo \"initialize Trafodion, upgrade;\" | sqlci" | tee -a initializeErrors.txt
+        foundError=$(grep "ERROR" initializeErrors.txt | wc -l)
+        if [ "$foundError" -ge "1" ];then 
+           ssh $STARTING_NODE "cd $MY_SQROOT/sql/scripts;  echo \"initialize Trafodion;\" | sqlci"
+        fi
         if [ "$?" != "0" ]; then
             echo "***ERROR: initialize Trafodion failed.  Check install log files for details." | tee -a $INSTALL_LOG
             exit -1;
         fi
     fi
+ 
 
-    # stop/start DCS (not needed now that sqstart will start dcs
-    echo "***INFO: skipping start-dcs.sh as DCS should be autostarted by sqstart, now." | tee -a $INSTALL_LOG
-    #DCS_VERSION=$(ls $MY_SQROOT | grep dcs)
-    #$MY_SQROOT/$DCS_VERSION/bin/stop-dcs.sh
-    #$MY_SQROOT/$DCS_VERSION/bin/start-dcs.sh
+    # Check that DCS has been started and start it if it hasn't
+    echo "***INFO: skipping dcsstart as DCS should be autostarted by sqstart." | tee -a $INSTALL_LOG
+    #$MY_SQROOT/sql/scripts/dcsstop
+    #$MY_SQROOT/sql/scripts/dcsstart
     #if [ "$?" != "0" ]; then
-    #    echo "***ERROR: start-dcs.sh failed.  Check install log files for details."
+    #    echo "***ERROR: dcsstart failed.  Check install log files for details."
     #    exit -1;
     #fi
 fi
