Scanner by default, fixes to trafodion_uninstaller
Scanner running by default.

Fixes to trafodion_uninstaller (removing --instance option).

Edit 1: Changed error message, added echo statements to
trafodion_uninstaller to clarify, fixed HDP version bug.
Change-Id: If6fe0bc88abbcb634eabf4a292a0975aa87f4cc0

diff --git a/installer/trafodion_uninstaller b/installer/trafodion_uninstaller
--- a/installer/trafodion_uninstaller
+++ b/installer/trafodion_uninstaller
@@ -19,20 +19,14 @@
 
 function print_usage {
 cat << EOF
-This script will uninstall a single instance or all of Trafodion.
+This script will uninstall Trafodion completely, including the Trafodion userid
+and its $HOME_DIR/$TRAF_USER directory. This must be run from a userid with 
+sudo access.
 
 Usage: $(basename $0) [options]
 
 Options:
     --help                  Print this message and exit.
-
-    --instance <dir-name>   Directory path of Trafodion instance to remove.
-                            This can be run from a Trafodion userid or userid with
-                            sudo access.
-
-    --all                   This will remove Trafodion completely, including the
-                            the Trafodion userid and its $HOME_DIR/trafodion directory.
-                            This must be run from a userid with sudo access.
 
 EOF
 }
@@ -59,18 +53,6 @@ UNINSTALL_DIR=""
 # Parse input parameters
 while [[ $# -gt 0 ]]; do
     case "$1" in
-        --instance)
-            if [[ -z "$2" ]]; then
-                echo "***ERROR: No value passed to param $1."
-                print_usage
-                exit -1
-            fi
-            UNINSTALL_DIR=$2
-            shift
-            ;;
-        --all)
-            UNINSTALL_ALL="Y"
-            ;;
         --help)
             print_usage
             exit -1
@@ -83,15 +65,18 @@ while [[ $# -gt 0 ]]; do
     shift
 done
 
-if [ -z "$UNINSTALL_DIR" ]; then
-    if [ "$UNINSTALL_ALL" != "Y" ]; then
-        echo "***ERROR: no directory to uninstall was specified or '--all' option was not used"
-        print_usage
-        exit -1
-    fi
+#=========================================
+#Confirmation 
+echo -n "Do you want to uninstall Trafodion (Everything will be removed)? (Y/N) "
+read v
+
+if [[ $v != "Y" ]] && [[ $v != "y" ]]; then
+  echo "***INFO: Exiting..."
+  exit
 fi
 
-# create logs directory and logfile name
+#=========================================
+#Create logs directory and logfile name
 timestamp=$(date +%F-%H-%M-%S)
 logsdir="/var/log/trafodion"
 logfile="$logsdir/uninstall_$timestamp.log"
@@ -105,64 +90,53 @@ else
     TRAF_PDSH="pdsh -S $MY_NODES"
 fi
 
-if [ "$UNINSTALL_ALL" != "Y" ]; then
-    # handle removing the current instance
-    # TODO: check that instance directory exists (do we need to do this?)
-    # TODO: maybe check that we are running from the Trafodion userid?
-
-    echo "***INFO: stopping Trafodion instance"
-    if [[ "$(whoami)" == "$TRAF_USER" ]]; then
-       sqstop
-       ckillall
-    else
-       sudo su $TRAF_USER --login --command "sqstop"
-       sudo su $TRAF_USER --login --command "ckillall"
-    fi    
-
-    # remove directory on all nodes
-    echo "***INFO: removing Trafodion build files"
-    $TRAF_PDSH rm -rf $UNINSTALL_DIR
-
-else
-    # check sudo access which is required for "--all" option
-    sudo echo "***INFO: testing sudo access"
-    if [ $? -ne 0 ]; then
-        echo "***ERROR: The '--all' option requires this script be run from a userid with sudo access."
-        exit -1
-    fi
-
-    echo "***INFO: NOTE, rpms that were installed will not be removed."
-
-    # handle removing all of Trafodion
-    echo "***INFO: stopping Trafodion instance"
-    sudo su $TRAF_USER --login --command "sqstop"
-    sudo su $TRAF_USER --login --command "ckillall"
-    sudo su $TRAF_USER --login --command "vncserver -kill :1"
-
-    echo "***INFO: restoring linux system files that were changed"
-    if [ $node_count -eq 1 ]; then
-        sudo cp $LOCAL_WORKDIR/etc_selinux_config_ORIGINAL /etc/selinux/config
-        sudo cp $LOCAL_WORKDIR/etc_security_limits.conf_ORIGINAL /etc/security/limits.conf
-        sudo rm /usr/share/cmf/lib/plugins/$HBASE_TRX 2>/dev/null
-        sudo rm /usr/lib/hbase/lib/$HBASE_TRX 2>/dev/null
-    else
-        pdsh $MY_NODES sudo cp $LOCAL_WORKDIR/etc_selinux_config_ORIGINAL /etc/selinux/config
-        pdsh $MY_NODES sudo cp $LOCAL_WORKDIR/etc_security_limits.conf_ORIGINAL /etc/security/limits.conf
-        pdsh $MY_NODES "sudo rm /usr/share/cmf/lib/plugins/$HBASE_TRX 2>/dev/null"
-        pdsh $MY_NODES "sudo rm /usr/lib/hbase/lib/$HBASE_TRX 2>/dev/null"
-    fi
-
-    echo "***INFO remove the Trafodion userid and group"
-    $TRAF_PDSH sudo rm -rf $TRAF_WORKDIR/$TRAF_USER
-    $TRAF_PDSH sudo rm -rf $LOCAL_WORKDIR/$TRAF_USER
-    $TRAF_PDSH sudo /usr/sbin/userdel --force --remove $TRAF_USER
-    $TRAF_PDSH sudo /usr/sbin/groupdel $TRAF_GROUP 2>/dev/null
-   
-    $TRAF_PDSH sudo rm -rf /usr/lib/trafodion*
-    $TRAF_PDSH sudo rm -rf /var/log/trafodion*
-
-    $TRAF_PDSH sudo rm -rf /etc/trafodion*
-    $TRAF_PDSH sudo rm -rf $LOCAL_WORKDIR/trafodion_config
-
+#Check sudo access which is required for "--all" option
+sudo echo "***INFO: testing sudo access"
+if [ $? -ne 0 ]; then
+   echo "***ERROR: trafodion_uninstaller requires sudo access."
+   exit -1
 fi
+
+echo "***INFO: NOTE, rpms that were installed will not be removed."
+
+#Handle removing all of Trafodion
+echo "***INFO: stopping Trafodion instance"
+sudo su $TRAF_USER --login --command "sqstop"
+sudo su $TRAF_USER --login --command "ckillall"
+sudo su $TRAF_USER --login --command "vncserver -kill :1"
+
+echo "***INFO: restoring linux system files that were changed"
+echo "***INFO: removing $HBASE_TRX from Hadoop directories"
+if [ $node_count -eq 1 ]; then
+   sudo cp $TRAF_WORKDIR/etc_selinux_config_ORIGINAL /etc/selinux/config
+   sudo cp $TRAF_WORKDIR/etc_security_limits.conf_ORIGINAL /etc/security/limits.conf
+   sudo rm /usr/share/cmf/lib/plugins/$HBASE_TRX 2>/dev/null
+   sudo rm /usr/lib/hbase/lib/$HBASE_TRX 2>/dev/null
+   sudo rm /usr/hdp/current/hbase-regionserver/lib/$HBASE_TRX 2>/dev/null
+else
+   pdsh $MY_NODES sudo cp $TRAF_WORKDIR/etc_selinux_config_ORIGINAL /etc/selinux/config
+   pdsh $MY_NODES sudo cp $TRAF_WORKDIR/etc_security_limits.conf_ORIGINAL /etc/security/limits.conf
+   pdsh $MY_NODES "sudo rm /usr/share/cmf/lib/plugins/$HBASE_TRX 2>/dev/null"
+   pdsh $MY_NODES "sudo rm /usr/lib/hbase/lib/$HBASE_TRX 2>/dev/null"
+   pdsh $MY_NODES "sudo rm /usr/hdp/current/hbase-regionserver/lib/$HBASE_TRX 2>/dev/null" 
+fi
+
+echo "***INFO remove the Trafodion userid and group"
+$TRAF_PDSH sudo rm -rf $TRAF_WORKDIR/$TRAF_USER
+$TRAF_PDSH sudo rm -rf $LOCAL_WORKDIR/$TRAF_USER
+$TRAF_PDSH sudo /usr/sbin/userdel --force --remove $TRAF_USER
+$TRAF_PDSH sudo /usr/sbin/groupdel $TRAF_GROUP 2>/dev/null
+
+echo "***INFO: removing all files from $SQ_ROOT"
+$TRAF_PDSH sudo rm -rf $SQ_ROOT
+ 
+echo "***INFO: removing all files from /usr/lib/trafodion and /var/log/trafodion"
+$TRAF_PDSH sudo rm -rf /usr/lib/trafodion*
+$TRAF_PDSH sudo rm -rf /var/log/trafodion*
+
+echo "***INFO: remvoing all files from /etc/trafodion"
+$TRAF_PDSH sudo rm -rf /etc/trafodion*
+$TRAF_PDSH sudo rm -rf $LOCAL_WORKDIR/trafodion_config
+
+echo "***INFO: Trafodion uninstall complete." 
 
