Simple security and scanner by default
The scanner will now be ran by default. The --no_scanner option can be
given to trafodion_install to by pass the scanner.

Simple security has now been automated. Users will be prompted to give
LDAP config information and then traf_authentication_setup will be ran
before sqstart.

Edit 1: Deleted unused variable and changed log directory for the
scanner logs.

Edit 2: Copyright

Edit 3: Changing the scanner to not be ran by default. Due to errors during
testing.

Change-Id: I60f75d11e7be615e475b3ffe4f9b4227ae6e7971

diff --git a/installer/traf_start b/installer/traf_start
--- a/installer/traf_start
+++ b/installer/traf_start
@@ -229,17 +229,58 @@ if [ "$node_count" -ne "1" ]; then
    fi
 fi
 
+#=========================================
+ # get first node listed in MY_NODES
+
+ if [[ "$node_count" -eq "1" ]]; then
+    STARTING_NODE=$NODE_LIST
+ else
+    STARTING_NODE=$(echo $MY_NODES | awk '{print $2}')
+ fi
+
+#==========================================
+#Copying traf_authentication_conf to scripts directory
+if [[ "$LDAP_SECURITY" == "Y" ]]; then
+   if [ "$node_count" -ne "1" ]; then
+      echo "***INFO: Copying $LDAP_AUTH_FILE to all nodes" | tee -a $INSTALL_LOG
+      pdcp $MY_NODES -r $HOME/$LDAP_AUTH_FILE $SQ_ROOT/sql/scripts/traf_authentication_config
+      if [ "$?" != "0" ]; then
+        echo "***ERROR: Unable to copy $LDAP_AUTH_FILE to all machines in this cluster.  Check install log files for details." | tee -a $INSTALL_LOG
+         exit -1;
+      fi
+   else
+      echo "***INFO: Copying $LDAP_AUTH_FILE to scripts directory." | tee -a $INSTALL_LOG
+      cp -rf $HOME/$TRAF_USER/$LDAP_AUTH_FILE $SQ_ROOT/sql/scripts/traf_authentication_config
+   fi
+
+   #Check traf_authentication_config for errors
+   echo "***INFO: Checking LDAP Configuration file for errors."
+   ldapconfigcheck -file $SQ_ROOT/sql/scripts/traf_authentication_config
+   if [ "$?" != "0" ]; then
+      echo "***ERROR: traf_authentication_config not configured correctly."
+      echo "***ERROR: Install will contiune WITHOUT simple security turned on."
+      echo "***ERROR: Please review wiki for manual steps to setup simple security." 
+   else
+      if [[ $LDAP_LEVEL == "1" ]]; then
+         echo "TLS_CACERT $HOME/$LDAP_CERT_BASE" > $HOME_DIR/trafodion/.ldaprc
+         echo "TLS_REQCERT demand" >> $HOME_DIR/trafodion/.ldaprc
+      fi
+      echo "***INFO: Enabling security. Running traf_authentication_setup"
+      ssh $STARTING_NODE "cd $MY_SQROOT/sql/scripts; traf_authentication_setup --setup --file traf_authentication_config"
+
+      if [[ $? != "0" ]]; then
+         echo "***WARNING: Error during script traf_authentication_setup"
+         echo "***WARNING: Install will continue WITHOUT simple security turned on."
+         echo "***WARNING: Please review wiki for manual steps to setup simple security."
+      fi
+   fi
+fi
+
+
 if [ "$START" == "N" ]; then
     echo "***INFO: Trafodion will not be started, skipping sqstart." | tee -a $INSTALL_LOG
 else
     echo "***INFO: starting Trafodion instance" | tee -a $INSTALL_LOG
-
-    # get first node listed in MY_NODES
-    if [[ "$node_count" -eq "1" ]]; then
-       STARTING_NODE=$NODE_LIST
-    else
-       STARTING_NODE=$(echo $MY_NODES | awk '{print $2}')  
-    fi
 
     ssh $STARTING_NODE "cd $MY_SQROOT/sql/scripts; sqstart"
     SQSTART_RC=$?
@@ -274,16 +315,6 @@ else
             exit -1;
         fi
     fi
- 
-
-    # Check that DCS has been started and start it if it hasn't
-    echo "***INFO: skipping dcsstart as DCS should be autostarted by sqstart." | tee -a $INSTALL_LOG
-    #$MY_SQROOT/sql/scripts/dcsstop
-    #$MY_SQROOT/sql/scripts/dcsstart
-    #if [ "$?" != "0" ]; then
-    #    echo "***ERROR: dcsstart failed.  Check install log files for details."
-    #    exit -1;
-    #fi
 fi
 
 #==========================================
