Added new HBase configurations and Bug Fix 1391962
New HBase configuration settings added.

Bug fix 1391962: A check has been added that makes sure that Trafodion
is installed on the same nodes that the Hadoop distro is installed on.
If they do not match trafodion_mods will exit and ask user to reinstall
using a correct list of nodes.

Change-Id: I0d5a2bca7636f3e7b3c4baa66c93b7e6c9c2d27b

diff --git a/installer/traf_hortonworks_mods b/installer/traf_hortonworks_mods
--- a/installer/traf_hortonworks_mods
+++ b/installer/traf_hortonworks_mods
@@ -193,6 +193,18 @@ if [ $? != 0 ]; then
     exit -1
 fi
 sleep 2
+$AMBARI_DIR/configs.sh -port $PORT set $(hostname --long) $CLUSTER_NAME hbase-site hbase.snapshot.master.timeoutMillis 600000
+if [ $? != 0 ]; then
+    echo "***INFO: unable to modify hbase.snapshot.master.timeoutMillis through Ambari's configs.sh script."
+    exit -1
+fi
+sleep 2
+$AMBARI_DIR/configs.sh -port $PORT set $(hostname --long) $CLUSTER_NAME hbase-site hbase.snapshot.region.timeout 600000
+if [ $? != 0 ]; then
+    echo "***INFO: unable to modify hbase.snapshot.region.timeout through Ambari's configs.sh script."
+    exit -1
+fi
+sleep 2
 echo
 echo "***WARNING: Please manually restart HBase through the Ambari web GUI"
 echo
