Added logic to wait for HDFS to leave safemode before continuing.
When HDFS Namenode restarts, it is temporarily in safemode which
makes HDFS read-only for a time.  This caused the hdfs mkdir/setfacl
commands to sometimes fail.

Added some additional error checks for HDFS commands and corrected some
message texts.

Change-Id: I026ef87f715edbdabfd0115d93ac0638dfdf0147

diff --git a/installer/traf_cloudera_mods98 b/installer/traf_cloudera_mods98
--- a/installer/traf_cloudera_mods98
+++ b/installer/traf_cloudera_mods98
@@ -228,7 +228,7 @@ rm $LOCAL_WORKDIR/traf_hbase_config_temp 2> /dev/null
 #=====================================
 # restart Cloudera to pick up all the changes just made
 poll_time=30
-echo "***INFO: restarting hbase to pickup Trafodion transaction jar"
+echo "***INFO: restarting Hadoop to pickup Trafodion transaction jar"
 echo "***INFO: ...polling every $poll_time seconds until restart is completed."
 restart_info=$(curl -X POST -u $ADMIN:$PASSWORD \
     http://$URL/api/v1/clusters/$CLUSTER_NAME/commands/restart)
@@ -252,18 +252,30 @@ done
 # make sure restart completed successfully
 failures=$(cat $LOCAL_WORKDIR/hbase_restart_status_temp | grep '"success" : false' | wc -l)
 if [ $failures -ne 0 ]; then
-    echo "***ERROR: Unable to restart HBase."
+    echo "***ERROR: Unable to restart Hadoop."
     exit -1
 fi
 
-echo "***INFO: HBase restart completed successfully"
+echo "***INFO: Hadoop restart completed successfully"
+
+# wait to make sure HDFS is fully restarted and out of safemode
+echo "***INFO: waiting for HDFS to exit safemode"
+sudo su hdfs --command "hdfs dfsadmin -safemode wait"
 
 #====================================================
 # NOTE: These command must be done AFTER acls are 
 #       enabled and HDFS has been restarted
 echo "***INFO: Setting HDFS ACLs for snapshot scan support"
 sudo su hdfs --command "hdfs dfs -mkdir -p /hbase/archive"
+if [ $? != 0 ]; then
+   echo "***ERROR: (hdfs dfs -mkdir -p /hbase/archive) command failed"
+   exit -1
+fi
 sudo su hdfs --command "hdfs dfs -chown hbase:hbase /hbase/archive"
+if [ $? != 0 ]; then
+   echo "***ERROR: (hdfs dfs -chown hbase:hbase /hbase/archive) command failed"
+   exit -1
+fi
 sudo su hdfs --command "hdfs dfs -setfacl -R -m user:$TRAF_USER:rwx /hbase/archive"
 if [ $? != 0 ]; then
    echo "***ERROR: (hdfs dfs -setfacl -R -m user:$TRAF_USER:rwx /hbase/archive) command failed"
diff --git a/installer/traf_hortonworks_mods98 b/installer/traf_hortonworks_mods98
--- a/installer/traf_hortonworks_mods98
+++ b/installer/traf_hortonworks_mods98
@@ -352,12 +352,24 @@ while [ $completed -eq 0 ]; do
     completed=$(cat $LOCAL_WORKDIR/traf_hdfs_restart_temp | grep '"request_status" : "COMPLETED"' | wc -l)
 done
 
+# wait to make sure HDFS is fully restarted and out of safemode
+echo "***INFO: waiting for HDFS to exit safemode"
+sudo su hdfs --command "hdfs dfsadmin -safemode wait"
+
 #=====================================
 # NOTE: These command must be done AFTER acls are 
 #       enabled and HDFS has been restarted
 echo "***INFO: Setting HDFS ACLs for snapshot scan support"
 sudo su hdfs --command "hdfs dfs -mkdir -p /apps/hbase/data/archive"
-sudo su hdfs --command "hdfs dfs -chown hbase:hdfs apps/hbase/data/archive"
+if [ $? != 0 ]; then
+   echo "***ERROR: (hdfs dfs -mkdir -p /apps/hbase/data/archive) command failed"
+   exit -1
+fi
+sudo su hdfs --command "hdfs dfs -chown hbase:hdfs /apps/hbase/data/archive"
+if [ $? != 0 ]; then
+   echo "***ERROR: (hdfs dfs -chown hbase:hdfs /apps/hbase/data/archive) command failed"
+   exit -1
+fi
 sudo su hdfs --command "hdfs dfs -setfacl -R -m user:$TRAF_USER:rwx /apps/hbase/data/archive"
 if [ $? != 0 ]; then
    echo "***ERROR: (hdfs dfs -setfacl -R -m mask::rwx /apps/hbase/data/archive) command failed"
@@ -378,6 +390,6 @@ fi
 # clean up files generated by Ambari's config.sh script
 rm $LOCAL_WORKDIR/doSet_version*
 
-echo "***INFO: HBase restart completed successfully"
+echo "***INFO: HDFS and HBase restart completed successfully"
 
 exit
