Adding installation of more rpm packages.
Added the following rpm packages:
pixman libXfont libX11 perl-Params-Validate perl-Time-HiRes

Made the optional group packages into separate installs
so we can more easily see which one failed.

Changed the EPEL rpm installation to use wget which will timeout
if unable to reach the download site.  The previous method of
using rpm directly could hang forever.

Change-Id: Ifad64df0f6ba493877ce777890ab17a8b193a3ff

diff --git a/installer/trafodion_setup b/installer/trafodion_setup
--- a/installer/trafodion_setup
+++ b/installer/trafodion_setup
@@ -314,8 +314,18 @@ if [ $node_count -ne 1 ]; then
 fi
 
 echo "***INFO: ... EPEL rpm"
-epel_rpm="http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm"
-$TRAF_PDSH sudo rpm -Uvh $epel_rpm 2>> $YUM_LOG >> $YUM_LOG
+epel_rpm="epel-release-6-8.noarch.rpm"
+wget http://download.fedoraproject.org/pub/epel/6/x86_64/$epel_rpm
+if [ $? != 0 ]; then
+    echo "***ERROR: Can't download EPEL rpm $epel_rpm"
+    exit -1
+fi
+if [ $node_count -ne 1 ]; then
+    pdcp $MY_NODES $epel_rpm $TRAF_WORKDIR
+else
+    cp $epel_rpm $TRAF_WORKDIR
+fi 
+$TRAF_PDSH sudo rpm -Uvh $TRAF_WORKDIR/$epel_rpm 2>> $YUM_LOG >> $YUM_LOG
 if [ $? != 0 ]; then
     echo "***ERROR: Can't install EPEL rpm $epel_rpm"
     exit -1
@@ -329,6 +339,7 @@ $TRAF_PDSH sudo yum-config-manager --enable RedHat-6-x86_64-Fedora-EPEL 2>> $YUM
 package_list="java-1.7.0-openjdk-devel qpid-cpp-client perl sqlite "
 package_list+=" expect perl-DBD-SQLite* protobuf xerces-c "
 package_list+=" libiodbc unixODBC tigervnc-server firefox "
+package_list+=" pixman libXfont libX11 perl-Params-Validate perl-Time-HiRes "
 for package in $package_list
 do
     echo "***INFO: ... $package"
@@ -340,10 +351,30 @@ do
 done
 
 #================================
-echo "***INFO: ... Desktop 'Desktop Platform' 'X Windows System' 'Fonts'"
-$TRAF_PDSH "sudo yum --assumeyes groupinstall \"Desktop\" \"Desktop Platform\" \"X Windows System\" \"Fonts\" " 2>> $YUM_LOG >> $YUM_LOG
+group_package_list="Desktop Fonts"
+for group_package in $group_package_list
+do
+    echo "***INFO: ... $group_package"
+    $TRAF_PDSH sudo yum --assumeyes groupinstall $group_package 2>> $YUM_LOG >> $YUM_LOG
+    if [ $? != 0 ]; then
+        echo "***WARNING: Can't group install optional group package $group_package"
+    fi
+done
+
+# need to do these separately because they have blanks in their name
+# and won't work properly in a list even if escaped with quotes
+group_package="Desktop Platform"
+echo "***INFO: ... $group_package"
+$TRAF_PDSH sudo yum --assumeyes groupinstall $group_package 2>> $YUM_LOG >> $YUM_LOG
 if [ $? != 0 ]; then
-    echo "***WARNING: Can't group install optional packages 'Desktop' 'Desktop Platform' 'X Windows System' 'Fonts'"
+    echo "***WARNING: Can't group install optional group package $group_package"
+fi
+
+group_package="X Windows System"
+echo "***INFO: ... $group_package"
+$TRAF_PDSH sudo yum --assumeyes groupinstall $group_package 2>> $YUM_LOG >> $YUM_LOG
+if [ $? != 0 ]; then
+    echo "***WARNING: Can't group install optional group package $group_package"
 fi
 
 #=======================================
